/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: livekit_metrics.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "livekit_metrics.pb-c.h"
void   livekit__metrics_batch__init
                     (Livekit__MetricsBatch         *message)
{
  static const Livekit__MetricsBatch init_value = LIVEKIT__METRICS_BATCH__INIT;
  *message = init_value;
}
size_t livekit__metrics_batch__get_packed_size
                     (const Livekit__MetricsBatch *message)
{
  assert(message->base.descriptor == &livekit__metrics_batch__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t livekit__metrics_batch__pack
                     (const Livekit__MetricsBatch *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &livekit__metrics_batch__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t livekit__metrics_batch__pack_to_buffer
                     (const Livekit__MetricsBatch *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &livekit__metrics_batch__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Livekit__MetricsBatch *
       livekit__metrics_batch__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Livekit__MetricsBatch *)
     protobuf_c_message_unpack (&livekit__metrics_batch__descriptor,
                                allocator, len, data);
}
void   livekit__metrics_batch__free_unpacked
                     (Livekit__MetricsBatch *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &livekit__metrics_batch__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   livekit__time_series_metric__init
                     (Livekit__TimeSeriesMetric         *message)
{
  static const Livekit__TimeSeriesMetric init_value = LIVEKIT__TIME_SERIES_METRIC__INIT;
  *message = init_value;
}
size_t livekit__time_series_metric__get_packed_size
                     (const Livekit__TimeSeriesMetric *message)
{
  assert(message->base.descriptor == &livekit__time_series_metric__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t livekit__time_series_metric__pack
                     (const Livekit__TimeSeriesMetric *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &livekit__time_series_metric__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t livekit__time_series_metric__pack_to_buffer
                     (const Livekit__TimeSeriesMetric *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &livekit__time_series_metric__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Livekit__TimeSeriesMetric *
       livekit__time_series_metric__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Livekit__TimeSeriesMetric *)
     protobuf_c_message_unpack (&livekit__time_series_metric__descriptor,
                                allocator, len, data);
}
void   livekit__time_series_metric__free_unpacked
                     (Livekit__TimeSeriesMetric *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &livekit__time_series_metric__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   livekit__metric_sample__init
                     (Livekit__MetricSample         *message)
{
  static const Livekit__MetricSample init_value = LIVEKIT__METRIC_SAMPLE__INIT;
  *message = init_value;
}
size_t livekit__metric_sample__get_packed_size
                     (const Livekit__MetricSample *message)
{
  assert(message->base.descriptor == &livekit__metric_sample__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t livekit__metric_sample__pack
                     (const Livekit__MetricSample *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &livekit__metric_sample__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t livekit__metric_sample__pack_to_buffer
                     (const Livekit__MetricSample *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &livekit__metric_sample__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Livekit__MetricSample *
       livekit__metric_sample__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Livekit__MetricSample *)
     protobuf_c_message_unpack (&livekit__metric_sample__descriptor,
                                allocator, len, data);
}
void   livekit__metric_sample__free_unpacked
                     (Livekit__MetricSample *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &livekit__metric_sample__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   livekit__event_metric__init
                     (Livekit__EventMetric         *message)
{
  static const Livekit__EventMetric init_value = LIVEKIT__EVENT_METRIC__INIT;
  *message = init_value;
}
size_t livekit__event_metric__get_packed_size
                     (const Livekit__EventMetric *message)
{
  assert(message->base.descriptor == &livekit__event_metric__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t livekit__event_metric__pack
                     (const Livekit__EventMetric *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &livekit__event_metric__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t livekit__event_metric__pack_to_buffer
                     (const Livekit__EventMetric *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &livekit__event_metric__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Livekit__EventMetric *
       livekit__event_metric__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Livekit__EventMetric *)
     protobuf_c_message_unpack (&livekit__event_metric__descriptor,
                                allocator, len, data);
}
void   livekit__event_metric__free_unpacked
                     (Livekit__EventMetric *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &livekit__event_metric__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor livekit__metrics_batch__field_descriptors[5] =
{
  {
    "timestamp_ms",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Livekit__MetricsBatch, timestamp_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "normalized_timestamp",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Livekit__MetricsBatch, normalized_timestamp),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "str_data",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Livekit__MetricsBatch, n_str_data),
    offsetof(Livekit__MetricsBatch, str_data),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_series",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Livekit__MetricsBatch, n_time_series),
    offsetof(Livekit__MetricsBatch, time_series),
    &livekit__time_series_metric__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "events",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Livekit__MetricsBatch, n_events),
    offsetof(Livekit__MetricsBatch, events),
    &livekit__event_metric__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned livekit__metrics_batch__field_indices_by_name[] = {
  4,   /* field[4] = events */
  1,   /* field[1] = normalized_timestamp */
  2,   /* field[2] = str_data */
  3,   /* field[3] = time_series */
  0,   /* field[0] = timestamp_ms */
};
static const ProtobufCIntRange livekit__metrics_batch__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor livekit__metrics_batch__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "livekit.MetricsBatch",
  "MetricsBatch",
  "Livekit__MetricsBatch",
  "livekit",
  sizeof(Livekit__MetricsBatch),
  5,
  livekit__metrics_batch__field_descriptors,
  livekit__metrics_batch__field_indices_by_name,
  1,  livekit__metrics_batch__number_ranges,
  (ProtobufCMessageInit) livekit__metrics_batch__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor livekit__time_series_metric__field_descriptors[5] =
{
  {
    "label",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Livekit__TimeSeriesMetric, label),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "participant_identity",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Livekit__TimeSeriesMetric, participant_identity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "track_sid",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Livekit__TimeSeriesMetric, track_sid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "samples",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Livekit__TimeSeriesMetric, n_samples),
    offsetof(Livekit__TimeSeriesMetric, samples),
    &livekit__metric_sample__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rid",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Livekit__TimeSeriesMetric, rid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned livekit__time_series_metric__field_indices_by_name[] = {
  0,   /* field[0] = label */
  1,   /* field[1] = participant_identity */
  4,   /* field[4] = rid */
  3,   /* field[3] = samples */
  2,   /* field[2] = track_sid */
};
static const ProtobufCIntRange livekit__time_series_metric__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor livekit__time_series_metric__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "livekit.TimeSeriesMetric",
  "TimeSeriesMetric",
  "Livekit__TimeSeriesMetric",
  "livekit",
  sizeof(Livekit__TimeSeriesMetric),
  5,
  livekit__time_series_metric__field_descriptors,
  livekit__time_series_metric__field_indices_by_name,
  1,  livekit__time_series_metric__number_ranges,
  (ProtobufCMessageInit) livekit__time_series_metric__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor livekit__metric_sample__field_descriptors[3] =
{
  {
    "timestamp_ms",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Livekit__MetricSample, timestamp_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "normalized_timestamp",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Livekit__MetricSample, normalized_timestamp),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Livekit__MetricSample, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned livekit__metric_sample__field_indices_by_name[] = {
  1,   /* field[1] = normalized_timestamp */
  0,   /* field[0] = timestamp_ms */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange livekit__metric_sample__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor livekit__metric_sample__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "livekit.MetricSample",
  "MetricSample",
  "Livekit__MetricSample",
  "livekit",
  sizeof(Livekit__MetricSample),
  3,
  livekit__metric_sample__field_descriptors,
  livekit__metric_sample__field_indices_by_name,
  1,  livekit__metric_sample__number_ranges,
  (ProtobufCMessageInit) livekit__metric_sample__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor livekit__event_metric__field_descriptors[9] =
{
  {
    "label",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Livekit__EventMetric, label),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "participant_identity",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Livekit__EventMetric, participant_identity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "track_sid",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Livekit__EventMetric, track_sid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_timestamp_ms",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Livekit__EventMetric, start_timestamp_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_timestamp_ms",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Livekit__EventMetric, _end_timestamp_ms_case),
    offsetof(Livekit__EventMetric, end_timestamp_ms),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "normalized_start_timestamp",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Livekit__EventMetric, normalized_start_timestamp),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "normalized_end_timestamp",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Livekit__EventMetric, _normalized_end_timestamp_case),
    offsetof(Livekit__EventMetric, normalized_end_timestamp),
    &google__protobuf__timestamp__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "metadata",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Livekit__EventMetric, metadata),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rid",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Livekit__EventMetric, rid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned livekit__event_metric__field_indices_by_name[] = {
  4,   /* field[4] = end_timestamp_ms */
  0,   /* field[0] = label */
  7,   /* field[7] = metadata */
  6,   /* field[6] = normalized_end_timestamp */
  5,   /* field[5] = normalized_start_timestamp */
  1,   /* field[1] = participant_identity */
  8,   /* field[8] = rid */
  3,   /* field[3] = start_timestamp_ms */
  2,   /* field[2] = track_sid */
};
static const ProtobufCIntRange livekit__event_metric__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor livekit__event_metric__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "livekit.EventMetric",
  "EventMetric",
  "Livekit__EventMetric",
  "livekit",
  sizeof(Livekit__EventMetric),
  9,
  livekit__event_metric__field_descriptors,
  livekit__event_metric__field_indices_by_name,
  1,  livekit__event_metric__number_ranges,
  (ProtobufCMessageInit) livekit__event_metric__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue livekit__metric_label__enum_values_by_number[21] =
{
  { "AGENTS_LLM_TTFT", "LIVEKIT__METRIC_LABEL__AGENTS_LLM_TTFT", 0 },
  { "AGENTS_STT_TTFT", "LIVEKIT__METRIC_LABEL__AGENTS_STT_TTFT", 1 },
  { "AGENTS_TTS_TTFB", "LIVEKIT__METRIC_LABEL__AGENTS_TTS_TTFB", 2 },
  { "CLIENT_VIDEO_SUBSCRIBER_FREEZE_COUNT", "LIVEKIT__METRIC_LABEL__CLIENT_VIDEO_SUBSCRIBER_FREEZE_COUNT", 3 },
  { "CLIENT_VIDEO_SUBSCRIBER_TOTAL_FREEZE_DURATION", "LIVEKIT__METRIC_LABEL__CLIENT_VIDEO_SUBSCRIBER_TOTAL_FREEZE_DURATION", 4 },
  { "CLIENT_VIDEO_SUBSCRIBER_PAUSE_COUNT", "LIVEKIT__METRIC_LABEL__CLIENT_VIDEO_SUBSCRIBER_PAUSE_COUNT", 5 },
  { "CLIENT_VIDEO_SUBSCRIBER_TOTAL_PAUSES_DURATION", "LIVEKIT__METRIC_LABEL__CLIENT_VIDEO_SUBSCRIBER_TOTAL_PAUSES_DURATION", 6 },
  { "CLIENT_AUDIO_SUBSCRIBER_CONCEALED_SAMPLES", "LIVEKIT__METRIC_LABEL__CLIENT_AUDIO_SUBSCRIBER_CONCEALED_SAMPLES", 7 },
  { "CLIENT_AUDIO_SUBSCRIBER_SILENT_CONCEALED_SAMPLES", "LIVEKIT__METRIC_LABEL__CLIENT_AUDIO_SUBSCRIBER_SILENT_CONCEALED_SAMPLES", 8 },
  { "CLIENT_AUDIO_SUBSCRIBER_CONCEALMENT_EVENTS", "LIVEKIT__METRIC_LABEL__CLIENT_AUDIO_SUBSCRIBER_CONCEALMENT_EVENTS", 9 },
  { "CLIENT_AUDIO_SUBSCRIBER_INTERRUPTION_COUNT", "LIVEKIT__METRIC_LABEL__CLIENT_AUDIO_SUBSCRIBER_INTERRUPTION_COUNT", 10 },
  { "CLIENT_AUDIO_SUBSCRIBER_TOTAL_INTERRUPTION_DURATION", "LIVEKIT__METRIC_LABEL__CLIENT_AUDIO_SUBSCRIBER_TOTAL_INTERRUPTION_DURATION", 11 },
  { "CLIENT_SUBSCRIBER_JITTER_BUFFER_DELAY", "LIVEKIT__METRIC_LABEL__CLIENT_SUBSCRIBER_JITTER_BUFFER_DELAY", 12 },
  { "CLIENT_SUBSCRIBER_JITTER_BUFFER_EMITTED_COUNT", "LIVEKIT__METRIC_LABEL__CLIENT_SUBSCRIBER_JITTER_BUFFER_EMITTED_COUNT", 13 },
  { "CLIENT_VIDEO_PUBLISHER_QUALITY_LIMITATION_DURATION_BANDWIDTH", "LIVEKIT__METRIC_LABEL__CLIENT_VIDEO_PUBLISHER_QUALITY_LIMITATION_DURATION_BANDWIDTH", 14 },
  { "CLIENT_VIDEO_PUBLISHER_QUALITY_LIMITATION_DURATION_CPU", "LIVEKIT__METRIC_LABEL__CLIENT_VIDEO_PUBLISHER_QUALITY_LIMITATION_DURATION_CPU", 15 },
  { "CLIENT_VIDEO_PUBLISHER_QUALITY_LIMITATION_DURATION_OTHER", "LIVEKIT__METRIC_LABEL__CLIENT_VIDEO_PUBLISHER_QUALITY_LIMITATION_DURATION_OTHER", 16 },
  { "PUBLISHER_RTT", "LIVEKIT__METRIC_LABEL__PUBLISHER_RTT", 17 },
  { "SERVER_MESH_RTT", "LIVEKIT__METRIC_LABEL__SERVER_MESH_RTT", 18 },
  { "SUBSCRIBER_RTT", "LIVEKIT__METRIC_LABEL__SUBSCRIBER_RTT", 19 },
  { "METRIC_LABEL_PREDEFINED_MAX_VALUE", "LIVEKIT__METRIC_LABEL__METRIC_LABEL_PREDEFINED_MAX_VALUE", 4096 },
};
static const ProtobufCIntRange livekit__metric_label__value_ranges[] = {
{0, 0},{4096, 20},{0, 21}
};
static const ProtobufCEnumValueIndex livekit__metric_label__enum_values_by_name[21] =
{
  { "AGENTS_LLM_TTFT", 0 },
  { "AGENTS_STT_TTFT", 1 },
  { "AGENTS_TTS_TTFB", 2 },
  { "CLIENT_AUDIO_SUBSCRIBER_CONCEALED_SAMPLES", 7 },
  { "CLIENT_AUDIO_SUBSCRIBER_CONCEALMENT_EVENTS", 9 },
  { "CLIENT_AUDIO_SUBSCRIBER_INTERRUPTION_COUNT", 10 },
  { "CLIENT_AUDIO_SUBSCRIBER_SILENT_CONCEALED_SAMPLES", 8 },
  { "CLIENT_AUDIO_SUBSCRIBER_TOTAL_INTERRUPTION_DURATION", 11 },
  { "CLIENT_SUBSCRIBER_JITTER_BUFFER_DELAY", 12 },
  { "CLIENT_SUBSCRIBER_JITTER_BUFFER_EMITTED_COUNT", 13 },
  { "CLIENT_VIDEO_PUBLISHER_QUALITY_LIMITATION_DURATION_BANDWIDTH", 14 },
  { "CLIENT_VIDEO_PUBLISHER_QUALITY_LIMITATION_DURATION_CPU", 15 },
  { "CLIENT_VIDEO_PUBLISHER_QUALITY_LIMITATION_DURATION_OTHER", 16 },
  { "CLIENT_VIDEO_SUBSCRIBER_FREEZE_COUNT", 3 },
  { "CLIENT_VIDEO_SUBSCRIBER_PAUSE_COUNT", 5 },
  { "CLIENT_VIDEO_SUBSCRIBER_TOTAL_FREEZE_DURATION", 4 },
  { "CLIENT_VIDEO_SUBSCRIBER_TOTAL_PAUSES_DURATION", 6 },
  { "METRIC_LABEL_PREDEFINED_MAX_VALUE", 20 },
  { "PUBLISHER_RTT", 17 },
  { "SERVER_MESH_RTT", 18 },
  { "SUBSCRIBER_RTT", 19 },
};
const ProtobufCEnumDescriptor livekit__metric_label__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "livekit.MetricLabel",
  "MetricLabel",
  "Livekit__MetricLabel",
  "livekit",
  21,
  livekit__metric_label__enum_values_by_number,
  21,
  livekit__metric_label__enum_values_by_name,
  2,
  livekit__metric_label__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
