/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: livekit_models.proto */

#ifndef PROTOBUF_C_livekit_5fmodels_2eproto__INCLUDED
#define PROTOBUF_C_livekit_5fmodels_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "google/protobuf/timestamp.pb-c.h"
#include "livekit_metrics.pb-c.h"

typedef struct Livekit__Pagination Livekit__Pagination;
typedef struct Livekit__ListUpdate Livekit__ListUpdate;
typedef struct Livekit__Room Livekit__Room;
typedef struct Livekit__Codec Livekit__Codec;
typedef struct Livekit__PlayoutDelay Livekit__PlayoutDelay;
typedef struct Livekit__ParticipantPermission Livekit__ParticipantPermission;
typedef struct Livekit__ParticipantInfo Livekit__ParticipantInfo;
typedef struct Livekit__ParticipantInfo__AttributesEntry Livekit__ParticipantInfo__AttributesEntry;
typedef struct Livekit__Encryption Livekit__Encryption;
typedef struct Livekit__SimulcastCodecInfo Livekit__SimulcastCodecInfo;
typedef struct Livekit__TrackInfo Livekit__TrackInfo;
typedef struct Livekit__VideoLayer Livekit__VideoLayer;
typedef struct Livekit__DataPacket Livekit__DataPacket;
typedef struct Livekit__ActiveSpeakerUpdate Livekit__ActiveSpeakerUpdate;
typedef struct Livekit__SpeakerInfo Livekit__SpeakerInfo;
typedef struct Livekit__UserPacket Livekit__UserPacket;
typedef struct Livekit__SipDTMF Livekit__SipDTMF;
typedef struct Livekit__Transcription Livekit__Transcription;
typedef struct Livekit__TranscriptionSegment Livekit__TranscriptionSegment;
typedef struct Livekit__ChatMessage Livekit__ChatMessage;
typedef struct Livekit__RpcRequest Livekit__RpcRequest;
typedef struct Livekit__RpcAck Livekit__RpcAck;
typedef struct Livekit__RpcResponse Livekit__RpcResponse;
typedef struct Livekit__RpcError Livekit__RpcError;
typedef struct Livekit__ParticipantTracks Livekit__ParticipantTracks;
typedef struct Livekit__ServerInfo Livekit__ServerInfo;
typedef struct Livekit__ClientInfo Livekit__ClientInfo;
typedef struct Livekit__ClientConfiguration Livekit__ClientConfiguration;
typedef struct Livekit__VideoConfiguration Livekit__VideoConfiguration;
typedef struct Livekit__DisabledCodecs Livekit__DisabledCodecs;
typedef struct Livekit__RTPDrift Livekit__RTPDrift;
typedef struct Livekit__RTPStats Livekit__RTPStats;
typedef struct Livekit__RTPStats__GapHistogramEntry Livekit__RTPStats__GapHistogramEntry;
typedef struct Livekit__RTCPSenderReportState Livekit__RTCPSenderReportState;
typedef struct Livekit__RTPForwarderState Livekit__RTPForwarderState;
typedef struct Livekit__RTPMungerState Livekit__RTPMungerState;
typedef struct Livekit__VP8MungerState Livekit__VP8MungerState;
typedef struct Livekit__TimedVersion Livekit__TimedVersion;
typedef struct Livekit__DataStream Livekit__DataStream;
typedef struct Livekit__DataStream__TextHeader Livekit__DataStream__TextHeader;
typedef struct Livekit__DataStream__ByteHeader Livekit__DataStream__ByteHeader;
typedef struct Livekit__DataStream__Header Livekit__DataStream__Header;
typedef struct Livekit__DataStream__Header__AttributesEntry Livekit__DataStream__Header__AttributesEntry;
typedef struct Livekit__DataStream__Chunk Livekit__DataStream__Chunk;
typedef struct Livekit__DataStream__Trailer Livekit__DataStream__Trailer;
typedef struct Livekit__DataStream__Trailer__AttributesEntry Livekit__DataStream__Trailer__AttributesEntry;
typedef struct Livekit__WebhookConfig Livekit__WebhookConfig;


/* --- enums --- */

typedef enum _Livekit__ParticipantInfo__State {
  /*
   * websocket' connected, but not offered yet
   */
  LIVEKIT__PARTICIPANT_INFO__STATE__JOINING = 0,
  /*
   * server received client offer
   */
  LIVEKIT__PARTICIPANT_INFO__STATE__JOINED = 1,
  /*
   * ICE connectivity established
   */
  LIVEKIT__PARTICIPANT_INFO__STATE__ACTIVE = 2,
  /*
   * WS disconnected
   */
  LIVEKIT__PARTICIPANT_INFO__STATE__DISCONNECTED = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__PARTICIPANT_INFO__STATE)
} Livekit__ParticipantInfo__State;
typedef enum _Livekit__ParticipantInfo__Kind {
  /*
   * standard participants, e.g. web clients
   */
  LIVEKIT__PARTICIPANT_INFO__KIND__STANDARD = 0,
  /*
   * only ingests streams
   */
  LIVEKIT__PARTICIPANT_INFO__KIND__INGRESS = 1,
  /*
   * only consumes streams
   */
  LIVEKIT__PARTICIPANT_INFO__KIND__EGRESS = 2,
  /*
   * SIP participants
   */
  LIVEKIT__PARTICIPANT_INFO__KIND__SIP = 3,
  /*
   * LiveKit agents
   */
  LIVEKIT__PARTICIPANT_INFO__KIND__AGENT = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__PARTICIPANT_INFO__KIND)
} Livekit__ParticipantInfo__Kind;
typedef enum _Livekit__ParticipantInfo__KindDetail {
  LIVEKIT__PARTICIPANT_INFO__KIND_DETAIL__CLOUD_AGENT = 0,
  LIVEKIT__PARTICIPANT_INFO__KIND_DETAIL__FORWARDED = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__PARTICIPANT_INFO__KIND_DETAIL)
} Livekit__ParticipantInfo__KindDetail;
typedef enum _Livekit__Encryption__Type {
  LIVEKIT__ENCRYPTION__TYPE__NONE = 0,
  LIVEKIT__ENCRYPTION__TYPE__GCM = 1,
  LIVEKIT__ENCRYPTION__TYPE__CUSTOM = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__ENCRYPTION__TYPE)
} Livekit__Encryption__Type;
typedef enum _Livekit__DataPacket__Kind {
  LIVEKIT__DATA_PACKET__KIND__RELIABLE = 0,
  LIVEKIT__DATA_PACKET__KIND__LOSSY = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__DATA_PACKET__KIND)
} Livekit__DataPacket__Kind;
typedef enum _Livekit__ServerInfo__Edition {
  LIVEKIT__SERVER_INFO__EDITION__Standard = 0,
  LIVEKIT__SERVER_INFO__EDITION__Cloud = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__SERVER_INFO__EDITION)
} Livekit__ServerInfo__Edition;
typedef enum _Livekit__ClientInfo__SDK {
  LIVEKIT__CLIENT_INFO__SDK__UNKNOWN = 0,
  LIVEKIT__CLIENT_INFO__SDK__JS = 1,
  LIVEKIT__CLIENT_INFO__SDK__SWIFT = 2,
  LIVEKIT__CLIENT_INFO__SDK__ANDROID = 3,
  LIVEKIT__CLIENT_INFO__SDK__FLUTTER = 4,
  LIVEKIT__CLIENT_INFO__SDK__GO = 5,
  LIVEKIT__CLIENT_INFO__SDK__UNITY = 6,
  LIVEKIT__CLIENT_INFO__SDK__REACT_NATIVE = 7,
  LIVEKIT__CLIENT_INFO__SDK__RUST = 8,
  LIVEKIT__CLIENT_INFO__SDK__PYTHON = 9,
  LIVEKIT__CLIENT_INFO__SDK__CPP = 10,
  LIVEKIT__CLIENT_INFO__SDK__UNITY_WEB = 11,
  LIVEKIT__CLIENT_INFO__SDK__NODE = 12,
  LIVEKIT__CLIENT_INFO__SDK__UNREAL = 13
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__CLIENT_INFO__SDK)
} Livekit__ClientInfo__SDK;
/*
 * enum for operation types (specific to TextHeader)
 */
typedef enum _Livekit__DataStream__OperationType {
  LIVEKIT__DATA_STREAM__OPERATION_TYPE__CREATE = 0,
  LIVEKIT__DATA_STREAM__OPERATION_TYPE__UPDATE = 1,
  LIVEKIT__DATA_STREAM__OPERATION_TYPE__DELETE = 2,
  LIVEKIT__DATA_STREAM__OPERATION_TYPE__REACTION = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__DATA_STREAM__OPERATION_TYPE)
} Livekit__DataStream__OperationType;
typedef enum _Livekit__AudioCodec {
  LIVEKIT__AUDIO_CODEC__DEFAULT_AC = 0,
  LIVEKIT__AUDIO_CODEC__OPUS = 1,
  LIVEKIT__AUDIO_CODEC__AAC = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__AUDIO_CODEC)
} Livekit__AudioCodec;
typedef enum _Livekit__VideoCodec {
  LIVEKIT__VIDEO_CODEC__DEFAULT_VC = 0,
  LIVEKIT__VIDEO_CODEC__H264_BASELINE = 1,
  LIVEKIT__VIDEO_CODEC__H264_MAIN = 2,
  LIVEKIT__VIDEO_CODEC__H264_HIGH = 3,
  LIVEKIT__VIDEO_CODEC__VP8 = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__VIDEO_CODEC)
} Livekit__VideoCodec;
typedef enum _Livekit__ImageCodec {
  LIVEKIT__IMAGE_CODEC__IC_DEFAULT = 0,
  LIVEKIT__IMAGE_CODEC__IC_JPEG = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__IMAGE_CODEC)
} Livekit__ImageCodec;
/*
 * Policy for publisher to handle subscribers that are unable to support the primary codec of a track
 */
typedef enum _Livekit__BackupCodecPolicy {
  /*
   * default behavior, the track prefer to regress to backup codec and all subscribers will receive the backup codec,
   * the sfu will try to regress codec if possible but not assured.
   */
  LIVEKIT__BACKUP_CODEC_POLICY__PREFER_REGRESSION = 0,
  /*
   * encoding/send the primary and backup codec simultaneously
   */
  LIVEKIT__BACKUP_CODEC_POLICY__SIMULCAST = 1,
  /*
   * force the track to regress to backup codec, this option can be used in video conference or the publisher has limited bandwidth/encoding power
   */
  LIVEKIT__BACKUP_CODEC_POLICY__REGRESSION = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__BACKUP_CODEC_POLICY)
} Livekit__BackupCodecPolicy;
typedef enum _Livekit__TrackType {
  LIVEKIT__TRACK_TYPE__AUDIO = 0,
  LIVEKIT__TRACK_TYPE__VIDEO = 1,
  LIVEKIT__TRACK_TYPE__DATA = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__TRACK_TYPE)
} Livekit__TrackType;
typedef enum _Livekit__TrackSource {
  LIVEKIT__TRACK_SOURCE__UNKNOWN = 0,
  LIVEKIT__TRACK_SOURCE__CAMERA = 1,
  LIVEKIT__TRACK_SOURCE__MICROPHONE = 2,
  LIVEKIT__TRACK_SOURCE__SCREEN_SHARE = 3,
  LIVEKIT__TRACK_SOURCE__SCREEN_SHARE_AUDIO = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__TRACK_SOURCE)
} Livekit__TrackSource;
typedef enum _Livekit__VideoQuality {
  LIVEKIT__VIDEO_QUALITY__LOW = 0,
  LIVEKIT__VIDEO_QUALITY__MEDIUM = 1,
  LIVEKIT__VIDEO_QUALITY__HIGH = 2,
  LIVEKIT__VIDEO_QUALITY__OFF = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__VIDEO_QUALITY)
} Livekit__VideoQuality;
typedef enum _Livekit__ConnectionQuality {
  LIVEKIT__CONNECTION_QUALITY__POOR = 0,
  LIVEKIT__CONNECTION_QUALITY__GOOD = 1,
  LIVEKIT__CONNECTION_QUALITY__EXCELLENT = 2,
  LIVEKIT__CONNECTION_QUALITY__LOST = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__CONNECTION_QUALITY)
} Livekit__ConnectionQuality;
typedef enum _Livekit__ClientConfigSetting {
  LIVEKIT__CLIENT_CONFIG_SETTING__UNSET = 0,
  LIVEKIT__CLIENT_CONFIG_SETTING__DISABLED = 1,
  LIVEKIT__CLIENT_CONFIG_SETTING__ENABLED = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__CLIENT_CONFIG_SETTING)
} Livekit__ClientConfigSetting;
typedef enum _Livekit__DisconnectReason {
  LIVEKIT__DISCONNECT_REASON__UNKNOWN_REASON = 0,
  /*
   * the client initiated the disconnect
   */
  LIVEKIT__DISCONNECT_REASON__CLIENT_INITIATED = 1,
  /*
   * another participant with the same identity has joined the room
   */
  LIVEKIT__DISCONNECT_REASON__DUPLICATE_IDENTITY = 2,
  /*
   * the server instance is shutting down
   */
  LIVEKIT__DISCONNECT_REASON__SERVER_SHUTDOWN = 3,
  /*
   * RoomService.RemoveParticipant was called
   */
  LIVEKIT__DISCONNECT_REASON__PARTICIPANT_REMOVED = 4,
  /*
   * RoomService.DeleteRoom was called
   */
  LIVEKIT__DISCONNECT_REASON__ROOM_DELETED = 5,
  /*
   * the client is attempting to resume a session, but server is not aware of it
   */
  LIVEKIT__DISCONNECT_REASON__STATE_MISMATCH = 6,
  /*
   * client was unable to connect fully
   */
  LIVEKIT__DISCONNECT_REASON__JOIN_FAILURE = 7,
  /*
   * Cloud-only, the server requested Participant to migrate the connection elsewhere
   */
  LIVEKIT__DISCONNECT_REASON__MIGRATION = 8,
  /*
   * the signal websocket was closed unexpectedly
   */
  LIVEKIT__DISCONNECT_REASON__SIGNAL_CLOSE = 9,
  /*
   * the room was closed, due to all Standard and Ingress participants having left
   */
  LIVEKIT__DISCONNECT_REASON__ROOM_CLOSED = 10,
  /*
   * SIP callee did not respond in time
   */
  LIVEKIT__DISCONNECT_REASON__USER_UNAVAILABLE = 11,
  /*
   * SIP callee rejected the call (busy)
   */
  LIVEKIT__DISCONNECT_REASON__USER_REJECTED = 12,
  /*
   * SIP protocol failure or unexpected response
   */
  LIVEKIT__DISCONNECT_REASON__SIP_TRUNK_FAILURE = 13,
  /*
   * server timed out a participant session
   */
  LIVEKIT__DISCONNECT_REASON__CONNECTION_TIMEOUT = 14,
  /*
   * media stream failure or media timeout
   */
  LIVEKIT__DISCONNECT_REASON__MEDIA_FAILURE = 15
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__DISCONNECT_REASON)
} Livekit__DisconnectReason;
typedef enum _Livekit__ReconnectReason {
  LIVEKIT__RECONNECT_REASON__RR_UNKNOWN = 0,
  LIVEKIT__RECONNECT_REASON__RR_SIGNAL_DISCONNECTED = 1,
  LIVEKIT__RECONNECT_REASON__RR_PUBLISHER_FAILED = 2,
  LIVEKIT__RECONNECT_REASON__RR_SUBSCRIBER_FAILED = 3,
  LIVEKIT__RECONNECT_REASON__RR_SWITCH_CANDIDATE = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__RECONNECT_REASON)
} Livekit__ReconnectReason;
typedef enum _Livekit__SubscriptionError {
  LIVEKIT__SUBSCRIPTION_ERROR__SE_UNKNOWN = 0,
  LIVEKIT__SUBSCRIPTION_ERROR__SE_CODEC_UNSUPPORTED = 1,
  LIVEKIT__SUBSCRIPTION_ERROR__SE_TRACK_NOTFOUND = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__SUBSCRIPTION_ERROR)
} Livekit__SubscriptionError;
typedef enum _Livekit__AudioTrackFeature {
  LIVEKIT__AUDIO_TRACK_FEATURE__TF_STEREO = 0,
  LIVEKIT__AUDIO_TRACK_FEATURE__TF_NO_DTX = 1,
  LIVEKIT__AUDIO_TRACK_FEATURE__TF_AUTO_GAIN_CONTROL = 2,
  LIVEKIT__AUDIO_TRACK_FEATURE__TF_ECHO_CANCELLATION = 3,
  LIVEKIT__AUDIO_TRACK_FEATURE__TF_NOISE_SUPPRESSION = 4,
  LIVEKIT__AUDIO_TRACK_FEATURE__TF_ENHANCED_NOISE_CANCELLATION = 5,
  /*
   * client will buffer audio once available and send it to the server via bytes stream once connected
   */
  LIVEKIT__AUDIO_TRACK_FEATURE__TF_PRECONNECT_BUFFER = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__AUDIO_TRACK_FEATURE)
} Livekit__AudioTrackFeature;

/* --- messages --- */

struct  Livekit__Pagination
{
  ProtobufCMessage base;
  /*
   * list entities which IDs are greater
   */
  char *after_id;
  int32_t limit;
};
#define LIVEKIT__PAGINATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__pagination__descriptor) \
, (char *)protobuf_c_empty_string, 0 }


/*
 * ListUpdate is used for updated APIs where 'repeated string' field is modified.
 */
struct  Livekit__ListUpdate
{
  ProtobufCMessage base;
  /*
   * set the field to a new list
   */
  size_t n_set;
  char **set;
};
#define LIVEKIT__LIST_UPDATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__list_update__descriptor) \
, 0,NULL }


struct  Livekit__Room
{
  ProtobufCMessage base;
  char *sid;
  char *name;
  uint32_t empty_timeout;
  uint32_t departure_timeout;
  uint32_t max_participants;
  int64_t creation_time;
  int64_t creation_time_ms;
  char *turn_password;
  size_t n_enabled_codecs;
  Livekit__Codec **enabled_codecs;
  char *metadata;
  uint32_t num_participants;
  uint32_t num_publishers;
  protobuf_c_boolean active_recording;
  Livekit__TimedVersion *version;
};
#define LIVEKIT__ROOM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__room__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0, 0, 0, (char *)protobuf_c_empty_string, 0,NULL, (char *)protobuf_c_empty_string, 0, 0, 0, NULL }


struct  Livekit__Codec
{
  ProtobufCMessage base;
  char *mime;
  char *fmtp_line;
};
#define LIVEKIT__CODEC__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__codec__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Livekit__PlayoutDelay
{
  ProtobufCMessage base;
  protobuf_c_boolean enabled;
  uint32_t min;
  uint32_t max;
};
#define LIVEKIT__PLAYOUT_DELAY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__playout_delay__descriptor) \
, 0, 0, 0 }


struct  Livekit__ParticipantPermission
{
  ProtobufCMessage base;
  /*
   * allow participant to subscribe to other tracks in the room
   */
  protobuf_c_boolean can_subscribe;
  /*
   * allow participant to publish new tracks to room
   */
  protobuf_c_boolean can_publish;
  /*
   * allow participant to publish data
   */
  protobuf_c_boolean can_publish_data;
  /*
   * sources that are allowed to be published
   */
  size_t n_can_publish_sources;
  Livekit__TrackSource *can_publish_sources;
  /*
   * indicates that it's hidden to others
   */
  protobuf_c_boolean hidden;
  /*
   * indicates it's a recorder instance
   * deprecated: use ParticipantInfo.kind instead
   */
  protobuf_c_boolean recorder PROTOBUF_C__DEPRECATED;
  /*
   * indicates that participant can update own metadata and attributes
   */
  protobuf_c_boolean can_update_metadata;
  /*
   * indicates that participant is an agent
   * deprecated: use ParticipantInfo.kind instead
   */
  protobuf_c_boolean agent PROTOBUF_C__DEPRECATED;
  /*
   * if a participant can subscribe to metrics
   */
  protobuf_c_boolean can_subscribe_metrics;
};
#define LIVEKIT__PARTICIPANT_PERMISSION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__participant_permission__descriptor) \
, 0, 0, 0, 0,NULL, 0, 0, 0, 0, 0 }


struct  Livekit__ParticipantInfo__AttributesEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define LIVEKIT__PARTICIPANT_INFO__ATTRIBUTES_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__participant_info__attributes_entry__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Livekit__ParticipantInfo
{
  ProtobufCMessage base;
  char *sid;
  char *identity;
  Livekit__ParticipantInfo__State state;
  size_t n_tracks;
  Livekit__TrackInfo **tracks;
  char *metadata;
  /*
   * timestamp when participant joined room, in seconds
   */
  int64_t joined_at;
  /*
   * timestamp when participant joined room, in milliseconds
   */
  int64_t joined_at_ms;
  char *name;
  uint32_t version;
  Livekit__ParticipantPermission *permission;
  char *region;
  /*
   * indicates the participant has an active publisher connection
   * and can publish to the server
   */
  protobuf_c_boolean is_publisher;
  Livekit__ParticipantInfo__Kind kind;
  size_t n_attributes;
  Livekit__ParticipantInfo__AttributesEntry **attributes;
  Livekit__DisconnectReason disconnect_reason;
  size_t n_kind_details;
  Livekit__ParticipantInfo__KindDetail *kind_details;
};
#define LIVEKIT__PARTICIPANT_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__participant_info__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, LIVEKIT__PARTICIPANT_INFO__STATE__JOINING, 0,NULL, (char *)protobuf_c_empty_string, 0, 0, (char *)protobuf_c_empty_string, 0, NULL, (char *)protobuf_c_empty_string, 0, LIVEKIT__PARTICIPANT_INFO__KIND__STANDARD, 0,NULL, LIVEKIT__DISCONNECT_REASON__UNKNOWN_REASON, 0,NULL }


struct  Livekit__Encryption
{
  ProtobufCMessage base;
};
#define LIVEKIT__ENCRYPTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__encryption__descriptor) \
 }


struct  Livekit__SimulcastCodecInfo
{
  ProtobufCMessage base;
  char *mime_type;
  char *mid;
  char *cid;
  size_t n_layers;
  Livekit__VideoLayer **layers;
};
#define LIVEKIT__SIMULCAST_CODEC_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__simulcast_codec_info__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL }


struct  Livekit__TrackInfo
{
  ProtobufCMessage base;
  char *sid;
  Livekit__TrackType type;
  char *name;
  protobuf_c_boolean muted;
  /*
   * original width of video (unset for audio)
   * clients may receive a lower resolution version with simulcast
   */
  uint32_t width;
  /*
   * original height of video (unset for audio)
   */
  uint32_t height;
  /*
   * true if track is simulcasted
   */
  protobuf_c_boolean simulcast;
  /*
   * true if DTX (Discontinuous Transmission) is disabled for audio
   */
  protobuf_c_boolean disable_dtx;
  /*
   * source of media
   */
  Livekit__TrackSource source;
  size_t n_layers;
  Livekit__VideoLayer **layers;
  /*
   * mime type of codec
   */
  char *mime_type;
  char *mid;
  size_t n_codecs;
  Livekit__SimulcastCodecInfo **codecs;
  protobuf_c_boolean stereo;
  /*
   * true if RED (Redundant Encoding) is disabled for audio
   */
  protobuf_c_boolean disable_red;
  Livekit__Encryption__Type encryption;
  char *stream;
  Livekit__TimedVersion *version;
  size_t n_audio_features;
  Livekit__AudioTrackFeature *audio_features;
  Livekit__BackupCodecPolicy backup_codec_policy;
};
#define LIVEKIT__TRACK_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__track_info__descriptor) \
, (char *)protobuf_c_empty_string, LIVEKIT__TRACK_TYPE__AUDIO, (char *)protobuf_c_empty_string, 0, 0, 0, 0, 0, LIVEKIT__TRACK_SOURCE__UNKNOWN, 0,NULL, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL, 0, 0, LIVEKIT__ENCRYPTION__TYPE__NONE, (char *)protobuf_c_empty_string, NULL, 0,NULL, LIVEKIT__BACKUP_CODEC_POLICY__PREFER_REGRESSION }


/*
 * provide information about available spatial layers
 */
struct  Livekit__VideoLayer
{
  ProtobufCMessage base;
  /*
   * for tracks with a single layer, this should be HIGH
   */
  Livekit__VideoQuality quality;
  uint32_t width;
  uint32_t height;
  /*
   * target bitrate in bit per second (bps), server will measure actual
   */
  uint32_t bitrate;
  uint32_t ssrc;
};
#define LIVEKIT__VIDEO_LAYER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__video_layer__descriptor) \
, LIVEKIT__VIDEO_QUALITY__LOW, 0, 0, 0, 0 }


typedef enum {
  LIVEKIT__DATA_PACKET__VALUE__NOT_SET = 0,
  LIVEKIT__DATA_PACKET__VALUE_USER = 2,
  LIVEKIT__DATA_PACKET__VALUE_SPEAKER = 3,
  LIVEKIT__DATA_PACKET__VALUE_SIP_DTMF = 6,
  LIVEKIT__DATA_PACKET__VALUE_TRANSCRIPTION = 7,
  LIVEKIT__DATA_PACKET__VALUE_METRICS = 8,
  LIVEKIT__DATA_PACKET__VALUE_CHAT_MESSAGE = 9,
  LIVEKIT__DATA_PACKET__VALUE_RPC_REQUEST = 10,
  LIVEKIT__DATA_PACKET__VALUE_RPC_ACK = 11,
  LIVEKIT__DATA_PACKET__VALUE_RPC_RESPONSE = 12,
  LIVEKIT__DATA_PACKET__VALUE_STREAM_HEADER = 13,
  LIVEKIT__DATA_PACKET__VALUE_STREAM_CHUNK = 14,
  LIVEKIT__DATA_PACKET__VALUE_STREAM_TRAILER = 15
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__DATA_PACKET__VALUE__CASE)
} Livekit__DataPacket__ValueCase;

/*
 * new DataPacket API
 */
struct  Livekit__DataPacket
{
  ProtobufCMessage base;
  Livekit__DataPacket__Kind kind PROTOBUF_C__DEPRECATED;
  /*
   * participant identity of user that sent the message
   */
  char *participant_identity;
  /*
   * identities of participants who will receive the message (sent to all by default)
   */
  size_t n_destination_identities;
  char **destination_identities;
  /*
   * sequence number of reliable packet
   */
  uint32_t sequence;
  /*
   * sid of the user that sent the message
   */
  char *participant_sid;
  Livekit__DataPacket__ValueCase value_case;
  union {
    Livekit__ChatMessage *chat_message;
    Livekit__MetricsBatch *metrics;
    Livekit__RpcAck *rpc_ack;
    Livekit__RpcRequest *rpc_request;
    Livekit__RpcResponse *rpc_response;
    Livekit__SipDTMF *sip_dtmf;
    Livekit__ActiveSpeakerUpdate *speaker PROTOBUF_C__DEPRECATED;
    Livekit__DataStream__Chunk *stream_chunk;
    Livekit__DataStream__Header *stream_header;
    Livekit__DataStream__Trailer *stream_trailer;
    Livekit__Transcription *transcription;
    Livekit__UserPacket *user;
  };
};
#define LIVEKIT__DATA_PACKET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__data_packet__descriptor) \
, LIVEKIT__DATA_PACKET__KIND__RELIABLE, (char *)protobuf_c_empty_string, 0,NULL, 0, (char *)protobuf_c_empty_string, LIVEKIT__DATA_PACKET__VALUE__NOT_SET, {0} }


struct  Livekit__ActiveSpeakerUpdate
{
  ProtobufCMessage base;
  size_t n_speakers;
  Livekit__SpeakerInfo **speakers;
};
#define LIVEKIT__ACTIVE_SPEAKER_UPDATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__active_speaker_update__descriptor) \
, 0,NULL }


struct  Livekit__SpeakerInfo
{
  ProtobufCMessage base;
  char *sid;
  /*
   * audio level, 0-1.0, 1 is loudest
   */
  float level;
  /*
   * true if speaker is currently active
   */
  protobuf_c_boolean active;
};
#define LIVEKIT__SPEAKER_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__speaker_info__descriptor) \
, (char *)protobuf_c_empty_string, 0, 0 }


typedef enum {
  LIVEKIT__USER_PACKET___TOPIC__NOT_SET = 0,
  LIVEKIT__USER_PACKET___TOPIC_TOPIC = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__USER_PACKET___TOPIC__CASE)
} Livekit__UserPacket__TopicCase;

typedef enum {
  LIVEKIT__USER_PACKET___ID__NOT_SET = 0,
  LIVEKIT__USER_PACKET___ID_ID = 8
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__USER_PACKET___ID__CASE)
} Livekit__UserPacket__IdCase;

typedef enum {
  LIVEKIT__USER_PACKET___START_TIME__NOT_SET = 0,
  LIVEKIT__USER_PACKET___START_TIME_START_TIME = 9
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__USER_PACKET___START_TIME__CASE)
} Livekit__UserPacket__StartTimeCase;

typedef enum {
  LIVEKIT__USER_PACKET___END_TIME__NOT_SET = 0,
  LIVEKIT__USER_PACKET___END_TIME_END_TIME = 10
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__USER_PACKET___END_TIME__CASE)
} Livekit__UserPacket__EndTimeCase;

struct  Livekit__UserPacket
{
  ProtobufCMessage base;
  /*
   * participant ID of user that sent the message
   */
  char *participant_sid PROTOBUF_C__DEPRECATED;
  char *participant_identity PROTOBUF_C__DEPRECATED;
  /*
   * user defined payload
   */
  ProtobufCBinaryData payload;
  /*
   * the ID of the participants who will receive the message (sent to all by default)
   */
  size_t n_destination_sids PROTOBUF_C__DEPRECATED;
  char **destination_sids PROTOBUF_C__DEPRECATED;
  /*
   * identities of participants who will receive the message (sent to all by default)
   */
  size_t n_destination_identities PROTOBUF_C__DEPRECATED;
  char **destination_identities PROTOBUF_C__DEPRECATED;
  /*
   * added by SDK to enable de-duping of messages, for INTERNAL USE ONLY
   */
  ProtobufCBinaryData nonce;
  Livekit__UserPacket__TopicCase _topic_case;
  union {
    /*
     * topic under which the message was published
     */
    char *topic;
  };
  Livekit__UserPacket__IdCase _id_case;
  union {
    /*
     * Unique ID to indentify the message
     */
    char *id;
  };
  Livekit__UserPacket__StartTimeCase _start_time_case;
  union {
    /*
     * start and end time allow relating the message to specific media time
     */
    uint64_t start_time;
  };
  Livekit__UserPacket__EndTimeCase _end_time_case;
  union {
    uint64_t end_time;
  };
};
#define LIVEKIT__USER_PACKET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__user_packet__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, {0,NULL}, 0,NULL, 0,NULL, {0,NULL}, LIVEKIT__USER_PACKET___TOPIC__NOT_SET, {0}, LIVEKIT__USER_PACKET___ID__NOT_SET, {0}, LIVEKIT__USER_PACKET___START_TIME__NOT_SET, {0}, LIVEKIT__USER_PACKET___END_TIME__NOT_SET, {0} }


struct  Livekit__SipDTMF
{
  ProtobufCMessage base;
  uint32_t code;
  char *digit;
};
#define LIVEKIT__SIP_DTMF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__sip_dtmf__descriptor) \
, 0, (char *)protobuf_c_empty_string }


struct  Livekit__Transcription
{
  ProtobufCMessage base;
  /*
   * Participant that got its speech transcribed
   */
  char *transcribed_participant_identity;
  char *track_id;
  size_t n_segments;
  Livekit__TranscriptionSegment **segments;
};
#define LIVEKIT__TRANSCRIPTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__transcription__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL }


struct  Livekit__TranscriptionSegment
{
  ProtobufCMessage base;
  char *id;
  char *text;
  uint64_t start_time;
  uint64_t end_time;
  protobuf_c_boolean final;
  char *language;
};
#define LIVEKIT__TRANSCRIPTION_SEGMENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__transcription_segment__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0, (char *)protobuf_c_empty_string }


typedef enum {
  LIVEKIT__CHAT_MESSAGE___EDIT_TIMESTAMP__NOT_SET = 0,
  LIVEKIT__CHAT_MESSAGE___EDIT_TIMESTAMP_EDIT_TIMESTAMP = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__CHAT_MESSAGE___EDIT_TIMESTAMP__CASE)
} Livekit__ChatMessage__EditTimestampCase;

struct  Livekit__ChatMessage
{
  ProtobufCMessage base;
  /*
   * uuid
   */
  char *id;
  int64_t timestamp;
  char *message;
  /*
   * true to remove message
   */
  protobuf_c_boolean deleted;
  /*
   * true if the chat message has been generated by an agent from a participant's audio transcription
   */
  protobuf_c_boolean generated;
  Livekit__ChatMessage__EditTimestampCase _edit_timestamp_case;
  union {
    /*
     * populated only if the intent is to edit/update an existing message
     */
    int64_t edit_timestamp;
  };
};
#define LIVEKIT__CHAT_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__chat_message__descriptor) \
, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, 0, 0, LIVEKIT__CHAT_MESSAGE___EDIT_TIMESTAMP__NOT_SET, {0} }


struct  Livekit__RpcRequest
{
  ProtobufCMessage base;
  char *id;
  char *method;
  char *payload;
  uint32_t response_timeout_ms;
  uint32_t version;
};
#define LIVEKIT__RPC_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__rpc_request__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0 }


struct  Livekit__RpcAck
{
  ProtobufCMessage base;
  char *request_id;
};
#define LIVEKIT__RPC_ACK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__rpc_ack__descriptor) \
, (char *)protobuf_c_empty_string }


typedef enum {
  LIVEKIT__RPC_RESPONSE__VALUE__NOT_SET = 0,
  LIVEKIT__RPC_RESPONSE__VALUE_PAYLOAD = 2,
  LIVEKIT__RPC_RESPONSE__VALUE_ERROR = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__RPC_RESPONSE__VALUE__CASE)
} Livekit__RpcResponse__ValueCase;

struct  Livekit__RpcResponse
{
  ProtobufCMessage base;
  char *request_id;
  Livekit__RpcResponse__ValueCase value_case;
  union {
    char *payload;
    Livekit__RpcError *error;
  };
};
#define LIVEKIT__RPC_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__rpc_response__descriptor) \
, (char *)protobuf_c_empty_string, LIVEKIT__RPC_RESPONSE__VALUE__NOT_SET, {0} }


struct  Livekit__RpcError
{
  ProtobufCMessage base;
  uint32_t code;
  char *message;
  char *data;
};
#define LIVEKIT__RPC_ERROR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__rpc_error__descriptor) \
, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Livekit__ParticipantTracks
{
  ProtobufCMessage base;
  /*
   * participant ID of participant to whom the tracks belong
   */
  char *participant_sid;
  size_t n_track_sids;
  char **track_sids;
};
#define LIVEKIT__PARTICIPANT_TRACKS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__participant_tracks__descriptor) \
, (char *)protobuf_c_empty_string, 0,NULL }


/*
 * details about the server
 */
struct  Livekit__ServerInfo
{
  ProtobufCMessage base;
  Livekit__ServerInfo__Edition edition;
  char *version;
  int32_t protocol;
  char *region;
  char *node_id;
  /*
   * additional debugging information. sent only if server is in development mode
   */
  char *debug_info;
  int32_t agent_protocol;
};
#define LIVEKIT__SERVER_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__server_info__descriptor) \
, LIVEKIT__SERVER_INFO__EDITION__Standard, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


/*
 * details about the client
 */
struct  Livekit__ClientInfo
{
  ProtobufCMessage base;
  Livekit__ClientInfo__SDK sdk;
  char *version;
  int32_t protocol;
  char *os;
  char *os_version;
  char *device_model;
  char *browser;
  char *browser_version;
  char *address;
  /*
   * wifi, wired, cellular, vpn, empty if not known
   */
  char *network;
  /*
   * comma separated list of additional LiveKit SDKs in use of this client, with versions
   * e.g. "components-js:1.2.3,track-processors-js:1.2.3"
   */
  char *other_sdks;
};
#define LIVEKIT__CLIENT_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__client_info__descriptor) \
, LIVEKIT__CLIENT_INFO__SDK__UNKNOWN, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * server provided client configuration
 */
struct  Livekit__ClientConfiguration
{
  ProtobufCMessage base;
  Livekit__VideoConfiguration *video;
  Livekit__VideoConfiguration *screen;
  Livekit__ClientConfigSetting resume_connection;
  Livekit__DisabledCodecs *disabled_codecs;
  Livekit__ClientConfigSetting force_relay;
};
#define LIVEKIT__CLIENT_CONFIGURATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__client_configuration__descriptor) \
, NULL, NULL, LIVEKIT__CLIENT_CONFIG_SETTING__UNSET, NULL, LIVEKIT__CLIENT_CONFIG_SETTING__UNSET }


struct  Livekit__VideoConfiguration
{
  ProtobufCMessage base;
  Livekit__ClientConfigSetting hardware_encoder;
};
#define LIVEKIT__VIDEO_CONFIGURATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__video_configuration__descriptor) \
, LIVEKIT__CLIENT_CONFIG_SETTING__UNSET }


struct  Livekit__DisabledCodecs
{
  ProtobufCMessage base;
  /*
   * disabled for both publish and subscribe
   */
  size_t n_codecs;
  Livekit__Codec **codecs;
  /*
   * only disable for publish
   */
  size_t n_publish;
  Livekit__Codec **publish;
};
#define LIVEKIT__DISABLED_CODECS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__disabled_codecs__descriptor) \
, 0,NULL, 0,NULL }


struct  Livekit__RTPDrift
{
  ProtobufCMessage base;
  Google__Protobuf__Timestamp *start_time;
  Google__Protobuf__Timestamp *end_time;
  double duration;
  uint64_t start_timestamp;
  uint64_t end_timestamp;
  uint64_t rtp_clock_ticks;
  int64_t drift_samples;
  double drift_ms;
  double clock_rate;
};
#define LIVEKIT__RTPDRIFT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__rtpdrift__descriptor) \
, NULL, NULL, 0, 0, 0, 0, 0, 0, 0 }


struct  Livekit__RTPStats__GapHistogramEntry
{
  ProtobufCMessage base;
  int32_t key;
  uint32_t value;
};
#define LIVEKIT__RTPSTATS__GAP_HISTOGRAM_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__rtpstats__gap_histogram_entry__descriptor) \
, 0, 0 }


struct  Livekit__RTPStats
{
  ProtobufCMessage base;
  Google__Protobuf__Timestamp *start_time;
  Google__Protobuf__Timestamp *end_time;
  double duration;
  uint32_t packets;
  double packet_rate;
  uint64_t bytes;
  uint64_t header_bytes;
  double bitrate;
  uint32_t packets_lost;
  double packet_loss_rate;
  float packet_loss_percentage;
  uint32_t packets_duplicate;
  double packet_duplicate_rate;
  uint64_t bytes_duplicate;
  uint64_t header_bytes_duplicate;
  double bitrate_duplicate;
  uint32_t packets_padding;
  double packet_padding_rate;
  uint64_t bytes_padding;
  uint64_t header_bytes_padding;
  double bitrate_padding;
  uint32_t packets_out_of_order;
  uint32_t frames;
  double frame_rate;
  double jitter_current;
  double jitter_max;
  size_t n_gap_histogram;
  Livekit__RTPStats__GapHistogramEntry **gap_histogram;
  uint32_t nacks;
  uint32_t nack_acks;
  uint32_t nack_misses;
  uint32_t nack_repeated;
  uint32_t plis;
  Google__Protobuf__Timestamp *last_pli;
  uint32_t firs;
  Google__Protobuf__Timestamp *last_fir;
  uint32_t rtt_current;
  uint32_t rtt_max;
  uint32_t key_frames;
  Google__Protobuf__Timestamp *last_key_frame;
  uint32_t layer_lock_plis;
  Google__Protobuf__Timestamp *last_layer_lock_pli;
  Livekit__RTPDrift *packet_drift;
  Livekit__RTPDrift *ntp_report_drift;
  Livekit__RTPDrift *rebased_report_drift;
  /*
   * NEXT_ID: 48
   */
  Livekit__RTPDrift *received_report_drift;
};
#define LIVEKIT__RTPSTATS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__rtpstats__descriptor) \
, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,NULL, 0, 0, 0, 0, 0, NULL, 0, NULL, 0, 0, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL }


struct  Livekit__RTCPSenderReportState
{
  ProtobufCMessage base;
  uint32_t rtp_timestamp;
  uint64_t rtp_timestamp_ext;
  uint64_t ntp_timestamp;
  /*
   * time at which this happened
   */
  int64_t at;
  int64_t at_adjusted;
  uint32_t packets;
  uint64_t octets;
};
#define LIVEKIT__RTCPSENDER_REPORT_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__rtcpsender_report_state__descriptor) \
, 0, 0, 0, 0, 0, 0, 0 }


typedef enum {
  LIVEKIT__RTPFORWARDER_STATE__CODEC_MUNGER__NOT_SET = 0,
  LIVEKIT__RTPFORWARDER_STATE__CODEC_MUNGER_VP8_MUNGER = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__RTPFORWARDER_STATE__CODEC_MUNGER__CASE)
} Livekit__RTPForwarderState__CodecMungerCase;

struct  Livekit__RTPForwarderState
{
  ProtobufCMessage base;
  protobuf_c_boolean started;
  int32_t reference_layer_spatial;
  int64_t pre_start_time;
  uint64_t ext_first_timestamp;
  uint64_t dummy_start_timestamp_offset;
  Livekit__RTPMungerState *rtp_munger;
  size_t n_sender_report_state;
  Livekit__RTCPSenderReportState **sender_report_state;
  Livekit__RTPForwarderState__CodecMungerCase codec_munger_case;
  union {
    Livekit__VP8MungerState *vp8_munger;
  };
};
#define LIVEKIT__RTPFORWARDER_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__rtpforwarder_state__descriptor) \
, 0, 0, 0, 0, 0, NULL, 0,NULL, LIVEKIT__RTPFORWARDER_STATE__CODEC_MUNGER__NOT_SET, {0} }


struct  Livekit__RTPMungerState
{
  ProtobufCMessage base;
  uint64_t ext_last_sequence_number;
  uint64_t ext_second_last_sequence_number;
  uint64_t ext_last_timestamp;
  uint64_t ext_second_last_timestamp;
  protobuf_c_boolean last_marker;
  protobuf_c_boolean second_last_marker;
};
#define LIVEKIT__RTPMUNGER_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__rtpmunger_state__descriptor) \
, 0, 0, 0, 0, 0, 0 }


struct  Livekit__VP8MungerState
{
  ProtobufCMessage base;
  int32_t ext_last_picture_id;
  protobuf_c_boolean picture_id_used;
  uint32_t last_tl0_pic_idx;
  protobuf_c_boolean tl0_pic_idx_used;
  protobuf_c_boolean tid_used;
  uint32_t last_key_idx;
  protobuf_c_boolean key_idx_used;
};
#define LIVEKIT__VP8_MUNGER_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__vp8_munger_state__descriptor) \
, 0, 0, 0, 0, 0, 0, 0 }


struct  Livekit__TimedVersion
{
  ProtobufCMessage base;
  int64_t unix_micro;
  int32_t ticks;
};
#define LIVEKIT__TIMED_VERSION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__timed_version__descriptor) \
, 0, 0 }


/*
 * header properties specific to text streams
 */
struct  Livekit__DataStream__TextHeader
{
  ProtobufCMessage base;
  Livekit__DataStream__OperationType operation_type;
  /*
   * Optional: Version for updates/edits
   */
  int32_t version;
  /*
   * Optional: Reply to specific message
   */
  char *reply_to_stream_id;
  /*
   * file attachments for text streams
   */
  size_t n_attached_stream_ids;
  char **attached_stream_ids;
  /*
   * true if the text has been generated by an agent from a participant's audio transcription
   */
  protobuf_c_boolean generated;
};
#define LIVEKIT__DATA_STREAM__TEXT_HEADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__data_stream__text_header__descriptor) \
, LIVEKIT__DATA_STREAM__OPERATION_TYPE__CREATE, 0, (char *)protobuf_c_empty_string, 0,NULL, 0 }


/*
 * header properties specific to byte or file streams
 */
struct  Livekit__DataStream__ByteHeader
{
  ProtobufCMessage base;
  char *name;
};
#define LIVEKIT__DATA_STREAM__BYTE_HEADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__data_stream__byte_header__descriptor) \
, (char *)protobuf_c_empty_string }


struct  Livekit__DataStream__Header__AttributesEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define LIVEKIT__DATA_STREAM__HEADER__ATTRIBUTES_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__data_stream__header__attributes_entry__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


typedef enum {
  LIVEKIT__DATA_STREAM__HEADER__CONTENT_HEADER__NOT_SET = 0,
  LIVEKIT__DATA_STREAM__HEADER__CONTENT_HEADER_TEXT_HEADER = 9,
  LIVEKIT__DATA_STREAM__HEADER__CONTENT_HEADER_BYTE_HEADER = 10
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__DATA_STREAM__HEADER__CONTENT_HEADER__CASE)
} Livekit__DataStream__Header__ContentHeaderCase;

typedef enum {
  LIVEKIT__DATA_STREAM__HEADER___TOTAL_LENGTH__NOT_SET = 0,
  LIVEKIT__DATA_STREAM__HEADER___TOTAL_LENGTH_TOTAL_LENGTH = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__DATA_STREAM__HEADER___TOTAL_LENGTH__CASE)
} Livekit__DataStream__Header__TotalLengthCase;

/*
 * main DataStream.Header that contains a oneof for specific headers
 */
struct  Livekit__DataStream__Header
{
  ProtobufCMessage base;
  /*
   * unique identifier for this data stream
   */
  char *stream_id;
  /*
   * using int64 for Unix timestamp
   */
  int64_t timestamp;
  char *topic;
  char *mime_type;
  /*
   * defaults to NONE
   */
  Livekit__Encryption__Type encryption_type;
  /*
   * user defined attributes map that can carry additional info
   */
  size_t n_attributes;
  Livekit__DataStream__Header__AttributesEntry **attributes;
  Livekit__DataStream__Header__ContentHeaderCase content_header_case;
  union {
    Livekit__DataStream__ByteHeader *byte_header;
    Livekit__DataStream__TextHeader *text_header;
  };
  Livekit__DataStream__Header__TotalLengthCase _total_length_case;
  union {
    /*
     * only populated for finite streams, if it's a stream of unknown size this stays empty
     */
    uint64_t total_length;
  };
};
#define LIVEKIT__DATA_STREAM__HEADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__data_stream__header__descriptor) \
, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, LIVEKIT__ENCRYPTION__TYPE__NONE, 0,NULL, LIVEKIT__DATA_STREAM__HEADER__CONTENT_HEADER__NOT_SET, {0}, LIVEKIT__DATA_STREAM__HEADER___TOTAL_LENGTH__NOT_SET, {0} }


typedef enum {
  LIVEKIT__DATA_STREAM__CHUNK___IV__NOT_SET = 0,
  LIVEKIT__DATA_STREAM__CHUNK___IV_IV = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__DATA_STREAM__CHUNK___IV__CASE)
} Livekit__DataStream__Chunk__IvCase;

struct  Livekit__DataStream__Chunk
{
  ProtobufCMessage base;
  /*
   * unique identifier for this data stream to map it to the correct header
   */
  char *stream_id;
  uint64_t chunk_index;
  /*
   * content as binary (bytes)
   */
  ProtobufCBinaryData content;
  /*
   * a version indicating that this chunk_index has been retroactively modified and the original one needs to be replaced
   */
  int32_t version;
  Livekit__DataStream__Chunk__IvCase _iv_case;
  union {
    /*
     * optional, initialization vector for AES-GCM encryption
     */
    ProtobufCBinaryData iv;
  };
};
#define LIVEKIT__DATA_STREAM__CHUNK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__data_stream__chunk__descriptor) \
, (char *)protobuf_c_empty_string, 0, {0,NULL}, 0, LIVEKIT__DATA_STREAM__CHUNK___IV__NOT_SET, { {0} } }


struct  Livekit__DataStream__Trailer__AttributesEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define LIVEKIT__DATA_STREAM__TRAILER__ATTRIBUTES_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__data_stream__trailer__attributes_entry__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Livekit__DataStream__Trailer
{
  ProtobufCMessage base;
  /*
   * unique identifier for this data stream
   */
  char *stream_id;
  /*
   * reason why the stream was closed (could contain "error" / "interrupted" / empty for expected end)
   */
  char *reason;
  /*
   * finalizing updates for the stream, can also include additional insights for errors or endTime for transcription
   */
  size_t n_attributes;
  Livekit__DataStream__Trailer__AttributesEntry **attributes;
};
#define LIVEKIT__DATA_STREAM__TRAILER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__data_stream__trailer__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL }


struct  Livekit__DataStream
{
  ProtobufCMessage base;
};
#define LIVEKIT__DATA_STREAM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__data_stream__descriptor) \
 }


struct  Livekit__WebhookConfig
{
  ProtobufCMessage base;
  char *url;
  char *signing_key;
};
#define LIVEKIT__WEBHOOK_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__webhook_config__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* Livekit__Pagination methods */
void   livekit__pagination__init
                     (Livekit__Pagination         *message);
size_t livekit__pagination__get_packed_size
                     (const Livekit__Pagination   *message);
size_t livekit__pagination__pack
                     (const Livekit__Pagination   *message,
                      uint8_t             *out);
size_t livekit__pagination__pack_to_buffer
                     (const Livekit__Pagination   *message,
                      ProtobufCBuffer     *buffer);
Livekit__Pagination *
       livekit__pagination__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__pagination__free_unpacked
                     (Livekit__Pagination *message,
                      ProtobufCAllocator *allocator);
/* Livekit__ListUpdate methods */
void   livekit__list_update__init
                     (Livekit__ListUpdate         *message);
size_t livekit__list_update__get_packed_size
                     (const Livekit__ListUpdate   *message);
size_t livekit__list_update__pack
                     (const Livekit__ListUpdate   *message,
                      uint8_t             *out);
size_t livekit__list_update__pack_to_buffer
                     (const Livekit__ListUpdate   *message,
                      ProtobufCBuffer     *buffer);
Livekit__ListUpdate *
       livekit__list_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__list_update__free_unpacked
                     (Livekit__ListUpdate *message,
                      ProtobufCAllocator *allocator);
/* Livekit__Room methods */
void   livekit__room__init
                     (Livekit__Room         *message);
size_t livekit__room__get_packed_size
                     (const Livekit__Room   *message);
size_t livekit__room__pack
                     (const Livekit__Room   *message,
                      uint8_t             *out);
size_t livekit__room__pack_to_buffer
                     (const Livekit__Room   *message,
                      ProtobufCBuffer     *buffer);
Livekit__Room *
       livekit__room__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__room__free_unpacked
                     (Livekit__Room *message,
                      ProtobufCAllocator *allocator);
/* Livekit__Codec methods */
void   livekit__codec__init
                     (Livekit__Codec         *message);
size_t livekit__codec__get_packed_size
                     (const Livekit__Codec   *message);
size_t livekit__codec__pack
                     (const Livekit__Codec   *message,
                      uint8_t             *out);
size_t livekit__codec__pack_to_buffer
                     (const Livekit__Codec   *message,
                      ProtobufCBuffer     *buffer);
Livekit__Codec *
       livekit__codec__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__codec__free_unpacked
                     (Livekit__Codec *message,
                      ProtobufCAllocator *allocator);
/* Livekit__PlayoutDelay methods */
void   livekit__playout_delay__init
                     (Livekit__PlayoutDelay         *message);
size_t livekit__playout_delay__get_packed_size
                     (const Livekit__PlayoutDelay   *message);
size_t livekit__playout_delay__pack
                     (const Livekit__PlayoutDelay   *message,
                      uint8_t             *out);
size_t livekit__playout_delay__pack_to_buffer
                     (const Livekit__PlayoutDelay   *message,
                      ProtobufCBuffer     *buffer);
Livekit__PlayoutDelay *
       livekit__playout_delay__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__playout_delay__free_unpacked
                     (Livekit__PlayoutDelay *message,
                      ProtobufCAllocator *allocator);
/* Livekit__ParticipantPermission methods */
void   livekit__participant_permission__init
                     (Livekit__ParticipantPermission         *message);
size_t livekit__participant_permission__get_packed_size
                     (const Livekit__ParticipantPermission   *message);
size_t livekit__participant_permission__pack
                     (const Livekit__ParticipantPermission   *message,
                      uint8_t             *out);
size_t livekit__participant_permission__pack_to_buffer
                     (const Livekit__ParticipantPermission   *message,
                      ProtobufCBuffer     *buffer);
Livekit__ParticipantPermission *
       livekit__participant_permission__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__participant_permission__free_unpacked
                     (Livekit__ParticipantPermission *message,
                      ProtobufCAllocator *allocator);
/* Livekit__ParticipantInfo__AttributesEntry methods */
void   livekit__participant_info__attributes_entry__init
                     (Livekit__ParticipantInfo__AttributesEntry         *message);
/* Livekit__ParticipantInfo methods */
void   livekit__participant_info__init
                     (Livekit__ParticipantInfo         *message);
size_t livekit__participant_info__get_packed_size
                     (const Livekit__ParticipantInfo   *message);
size_t livekit__participant_info__pack
                     (const Livekit__ParticipantInfo   *message,
                      uint8_t             *out);
size_t livekit__participant_info__pack_to_buffer
                     (const Livekit__ParticipantInfo   *message,
                      ProtobufCBuffer     *buffer);
Livekit__ParticipantInfo *
       livekit__participant_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__participant_info__free_unpacked
                     (Livekit__ParticipantInfo *message,
                      ProtobufCAllocator *allocator);
/* Livekit__Encryption methods */
void   livekit__encryption__init
                     (Livekit__Encryption         *message);
size_t livekit__encryption__get_packed_size
                     (const Livekit__Encryption   *message);
size_t livekit__encryption__pack
                     (const Livekit__Encryption   *message,
                      uint8_t             *out);
size_t livekit__encryption__pack_to_buffer
                     (const Livekit__Encryption   *message,
                      ProtobufCBuffer     *buffer);
Livekit__Encryption *
       livekit__encryption__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__encryption__free_unpacked
                     (Livekit__Encryption *message,
                      ProtobufCAllocator *allocator);
/* Livekit__SimulcastCodecInfo methods */
void   livekit__simulcast_codec_info__init
                     (Livekit__SimulcastCodecInfo         *message);
size_t livekit__simulcast_codec_info__get_packed_size
                     (const Livekit__SimulcastCodecInfo   *message);
size_t livekit__simulcast_codec_info__pack
                     (const Livekit__SimulcastCodecInfo   *message,
                      uint8_t             *out);
size_t livekit__simulcast_codec_info__pack_to_buffer
                     (const Livekit__SimulcastCodecInfo   *message,
                      ProtobufCBuffer     *buffer);
Livekit__SimulcastCodecInfo *
       livekit__simulcast_codec_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__simulcast_codec_info__free_unpacked
                     (Livekit__SimulcastCodecInfo *message,
                      ProtobufCAllocator *allocator);
/* Livekit__TrackInfo methods */
void   livekit__track_info__init
                     (Livekit__TrackInfo         *message);
size_t livekit__track_info__get_packed_size
                     (const Livekit__TrackInfo   *message);
size_t livekit__track_info__pack
                     (const Livekit__TrackInfo   *message,
                      uint8_t             *out);
size_t livekit__track_info__pack_to_buffer
                     (const Livekit__TrackInfo   *message,
                      ProtobufCBuffer     *buffer);
Livekit__TrackInfo *
       livekit__track_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__track_info__free_unpacked
                     (Livekit__TrackInfo *message,
                      ProtobufCAllocator *allocator);
/* Livekit__VideoLayer methods */
void   livekit__video_layer__init
                     (Livekit__VideoLayer         *message);
size_t livekit__video_layer__get_packed_size
                     (const Livekit__VideoLayer   *message);
size_t livekit__video_layer__pack
                     (const Livekit__VideoLayer   *message,
                      uint8_t             *out);
size_t livekit__video_layer__pack_to_buffer
                     (const Livekit__VideoLayer   *message,
                      ProtobufCBuffer     *buffer);
Livekit__VideoLayer *
       livekit__video_layer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__video_layer__free_unpacked
                     (Livekit__VideoLayer *message,
                      ProtobufCAllocator *allocator);
/* Livekit__DataPacket methods */
void   livekit__data_packet__init
                     (Livekit__DataPacket         *message);
size_t livekit__data_packet__get_packed_size
                     (const Livekit__DataPacket   *message);
size_t livekit__data_packet__pack
                     (const Livekit__DataPacket   *message,
                      uint8_t             *out);
size_t livekit__data_packet__pack_to_buffer
                     (const Livekit__DataPacket   *message,
                      ProtobufCBuffer     *buffer);
Livekit__DataPacket *
       livekit__data_packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__data_packet__free_unpacked
                     (Livekit__DataPacket *message,
                      ProtobufCAllocator *allocator);
/* Livekit__ActiveSpeakerUpdate methods */
void   livekit__active_speaker_update__init
                     (Livekit__ActiveSpeakerUpdate         *message);
size_t livekit__active_speaker_update__get_packed_size
                     (const Livekit__ActiveSpeakerUpdate   *message);
size_t livekit__active_speaker_update__pack
                     (const Livekit__ActiveSpeakerUpdate   *message,
                      uint8_t             *out);
size_t livekit__active_speaker_update__pack_to_buffer
                     (const Livekit__ActiveSpeakerUpdate   *message,
                      ProtobufCBuffer     *buffer);
Livekit__ActiveSpeakerUpdate *
       livekit__active_speaker_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__active_speaker_update__free_unpacked
                     (Livekit__ActiveSpeakerUpdate *message,
                      ProtobufCAllocator *allocator);
/* Livekit__SpeakerInfo methods */
void   livekit__speaker_info__init
                     (Livekit__SpeakerInfo         *message);
size_t livekit__speaker_info__get_packed_size
                     (const Livekit__SpeakerInfo   *message);
size_t livekit__speaker_info__pack
                     (const Livekit__SpeakerInfo   *message,
                      uint8_t             *out);
size_t livekit__speaker_info__pack_to_buffer
                     (const Livekit__SpeakerInfo   *message,
                      ProtobufCBuffer     *buffer);
Livekit__SpeakerInfo *
       livekit__speaker_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__speaker_info__free_unpacked
                     (Livekit__SpeakerInfo *message,
                      ProtobufCAllocator *allocator);
/* Livekit__UserPacket methods */
void   livekit__user_packet__init
                     (Livekit__UserPacket         *message);
size_t livekit__user_packet__get_packed_size
                     (const Livekit__UserPacket   *message);
size_t livekit__user_packet__pack
                     (const Livekit__UserPacket   *message,
                      uint8_t             *out);
size_t livekit__user_packet__pack_to_buffer
                     (const Livekit__UserPacket   *message,
                      ProtobufCBuffer     *buffer);
Livekit__UserPacket *
       livekit__user_packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__user_packet__free_unpacked
                     (Livekit__UserPacket *message,
                      ProtobufCAllocator *allocator);
/* Livekit__SipDTMF methods */
void   livekit__sip_dtmf__init
                     (Livekit__SipDTMF         *message);
size_t livekit__sip_dtmf__get_packed_size
                     (const Livekit__SipDTMF   *message);
size_t livekit__sip_dtmf__pack
                     (const Livekit__SipDTMF   *message,
                      uint8_t             *out);
size_t livekit__sip_dtmf__pack_to_buffer
                     (const Livekit__SipDTMF   *message,
                      ProtobufCBuffer     *buffer);
Livekit__SipDTMF *
       livekit__sip_dtmf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__sip_dtmf__free_unpacked
                     (Livekit__SipDTMF *message,
                      ProtobufCAllocator *allocator);
/* Livekit__Transcription methods */
void   livekit__transcription__init
                     (Livekit__Transcription         *message);
size_t livekit__transcription__get_packed_size
                     (const Livekit__Transcription   *message);
size_t livekit__transcription__pack
                     (const Livekit__Transcription   *message,
                      uint8_t             *out);
size_t livekit__transcription__pack_to_buffer
                     (const Livekit__Transcription   *message,
                      ProtobufCBuffer     *buffer);
Livekit__Transcription *
       livekit__transcription__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__transcription__free_unpacked
                     (Livekit__Transcription *message,
                      ProtobufCAllocator *allocator);
/* Livekit__TranscriptionSegment methods */
void   livekit__transcription_segment__init
                     (Livekit__TranscriptionSegment         *message);
size_t livekit__transcription_segment__get_packed_size
                     (const Livekit__TranscriptionSegment   *message);
size_t livekit__transcription_segment__pack
                     (const Livekit__TranscriptionSegment   *message,
                      uint8_t             *out);
size_t livekit__transcription_segment__pack_to_buffer
                     (const Livekit__TranscriptionSegment   *message,
                      ProtobufCBuffer     *buffer);
Livekit__TranscriptionSegment *
       livekit__transcription_segment__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__transcription_segment__free_unpacked
                     (Livekit__TranscriptionSegment *message,
                      ProtobufCAllocator *allocator);
/* Livekit__ChatMessage methods */
void   livekit__chat_message__init
                     (Livekit__ChatMessage         *message);
size_t livekit__chat_message__get_packed_size
                     (const Livekit__ChatMessage   *message);
size_t livekit__chat_message__pack
                     (const Livekit__ChatMessage   *message,
                      uint8_t             *out);
size_t livekit__chat_message__pack_to_buffer
                     (const Livekit__ChatMessage   *message,
                      ProtobufCBuffer     *buffer);
Livekit__ChatMessage *
       livekit__chat_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__chat_message__free_unpacked
                     (Livekit__ChatMessage *message,
                      ProtobufCAllocator *allocator);
/* Livekit__RpcRequest methods */
void   livekit__rpc_request__init
                     (Livekit__RpcRequest         *message);
size_t livekit__rpc_request__get_packed_size
                     (const Livekit__RpcRequest   *message);
size_t livekit__rpc_request__pack
                     (const Livekit__RpcRequest   *message,
                      uint8_t             *out);
size_t livekit__rpc_request__pack_to_buffer
                     (const Livekit__RpcRequest   *message,
                      ProtobufCBuffer     *buffer);
Livekit__RpcRequest *
       livekit__rpc_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__rpc_request__free_unpacked
                     (Livekit__RpcRequest *message,
                      ProtobufCAllocator *allocator);
/* Livekit__RpcAck methods */
void   livekit__rpc_ack__init
                     (Livekit__RpcAck         *message);
size_t livekit__rpc_ack__get_packed_size
                     (const Livekit__RpcAck   *message);
size_t livekit__rpc_ack__pack
                     (const Livekit__RpcAck   *message,
                      uint8_t             *out);
size_t livekit__rpc_ack__pack_to_buffer
                     (const Livekit__RpcAck   *message,
                      ProtobufCBuffer     *buffer);
Livekit__RpcAck *
       livekit__rpc_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__rpc_ack__free_unpacked
                     (Livekit__RpcAck *message,
                      ProtobufCAllocator *allocator);
/* Livekit__RpcResponse methods */
void   livekit__rpc_response__init
                     (Livekit__RpcResponse         *message);
size_t livekit__rpc_response__get_packed_size
                     (const Livekit__RpcResponse   *message);
size_t livekit__rpc_response__pack
                     (const Livekit__RpcResponse   *message,
                      uint8_t             *out);
size_t livekit__rpc_response__pack_to_buffer
                     (const Livekit__RpcResponse   *message,
                      ProtobufCBuffer     *buffer);
Livekit__RpcResponse *
       livekit__rpc_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__rpc_response__free_unpacked
                     (Livekit__RpcResponse *message,
                      ProtobufCAllocator *allocator);
/* Livekit__RpcError methods */
void   livekit__rpc_error__init
                     (Livekit__RpcError         *message);
size_t livekit__rpc_error__get_packed_size
                     (const Livekit__RpcError   *message);
size_t livekit__rpc_error__pack
                     (const Livekit__RpcError   *message,
                      uint8_t             *out);
size_t livekit__rpc_error__pack_to_buffer
                     (const Livekit__RpcError   *message,
                      ProtobufCBuffer     *buffer);
Livekit__RpcError *
       livekit__rpc_error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__rpc_error__free_unpacked
                     (Livekit__RpcError *message,
                      ProtobufCAllocator *allocator);
/* Livekit__ParticipantTracks methods */
void   livekit__participant_tracks__init
                     (Livekit__ParticipantTracks         *message);
size_t livekit__participant_tracks__get_packed_size
                     (const Livekit__ParticipantTracks   *message);
size_t livekit__participant_tracks__pack
                     (const Livekit__ParticipantTracks   *message,
                      uint8_t             *out);
size_t livekit__participant_tracks__pack_to_buffer
                     (const Livekit__ParticipantTracks   *message,
                      ProtobufCBuffer     *buffer);
Livekit__ParticipantTracks *
       livekit__participant_tracks__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__participant_tracks__free_unpacked
                     (Livekit__ParticipantTracks *message,
                      ProtobufCAllocator *allocator);
/* Livekit__ServerInfo methods */
void   livekit__server_info__init
                     (Livekit__ServerInfo         *message);
size_t livekit__server_info__get_packed_size
                     (const Livekit__ServerInfo   *message);
size_t livekit__server_info__pack
                     (const Livekit__ServerInfo   *message,
                      uint8_t             *out);
size_t livekit__server_info__pack_to_buffer
                     (const Livekit__ServerInfo   *message,
                      ProtobufCBuffer     *buffer);
Livekit__ServerInfo *
       livekit__server_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__server_info__free_unpacked
                     (Livekit__ServerInfo *message,
                      ProtobufCAllocator *allocator);
/* Livekit__ClientInfo methods */
void   livekit__client_info__init
                     (Livekit__ClientInfo         *message);
size_t livekit__client_info__get_packed_size
                     (const Livekit__ClientInfo   *message);
size_t livekit__client_info__pack
                     (const Livekit__ClientInfo   *message,
                      uint8_t             *out);
size_t livekit__client_info__pack_to_buffer
                     (const Livekit__ClientInfo   *message,
                      ProtobufCBuffer     *buffer);
Livekit__ClientInfo *
       livekit__client_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__client_info__free_unpacked
                     (Livekit__ClientInfo *message,
                      ProtobufCAllocator *allocator);
/* Livekit__ClientConfiguration methods */
void   livekit__client_configuration__init
                     (Livekit__ClientConfiguration         *message);
size_t livekit__client_configuration__get_packed_size
                     (const Livekit__ClientConfiguration   *message);
size_t livekit__client_configuration__pack
                     (const Livekit__ClientConfiguration   *message,
                      uint8_t             *out);
size_t livekit__client_configuration__pack_to_buffer
                     (const Livekit__ClientConfiguration   *message,
                      ProtobufCBuffer     *buffer);
Livekit__ClientConfiguration *
       livekit__client_configuration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__client_configuration__free_unpacked
                     (Livekit__ClientConfiguration *message,
                      ProtobufCAllocator *allocator);
/* Livekit__VideoConfiguration methods */
void   livekit__video_configuration__init
                     (Livekit__VideoConfiguration         *message);
size_t livekit__video_configuration__get_packed_size
                     (const Livekit__VideoConfiguration   *message);
size_t livekit__video_configuration__pack
                     (const Livekit__VideoConfiguration   *message,
                      uint8_t             *out);
size_t livekit__video_configuration__pack_to_buffer
                     (const Livekit__VideoConfiguration   *message,
                      ProtobufCBuffer     *buffer);
Livekit__VideoConfiguration *
       livekit__video_configuration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__video_configuration__free_unpacked
                     (Livekit__VideoConfiguration *message,
                      ProtobufCAllocator *allocator);
/* Livekit__DisabledCodecs methods */
void   livekit__disabled_codecs__init
                     (Livekit__DisabledCodecs         *message);
size_t livekit__disabled_codecs__get_packed_size
                     (const Livekit__DisabledCodecs   *message);
size_t livekit__disabled_codecs__pack
                     (const Livekit__DisabledCodecs   *message,
                      uint8_t             *out);
size_t livekit__disabled_codecs__pack_to_buffer
                     (const Livekit__DisabledCodecs   *message,
                      ProtobufCBuffer     *buffer);
Livekit__DisabledCodecs *
       livekit__disabled_codecs__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__disabled_codecs__free_unpacked
                     (Livekit__DisabledCodecs *message,
                      ProtobufCAllocator *allocator);
/* Livekit__RTPDrift methods */
void   livekit__rtpdrift__init
                     (Livekit__RTPDrift         *message);
size_t livekit__rtpdrift__get_packed_size
                     (const Livekit__RTPDrift   *message);
size_t livekit__rtpdrift__pack
                     (const Livekit__RTPDrift   *message,
                      uint8_t             *out);
size_t livekit__rtpdrift__pack_to_buffer
                     (const Livekit__RTPDrift   *message,
                      ProtobufCBuffer     *buffer);
Livekit__RTPDrift *
       livekit__rtpdrift__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__rtpdrift__free_unpacked
                     (Livekit__RTPDrift *message,
                      ProtobufCAllocator *allocator);
/* Livekit__RTPStats__GapHistogramEntry methods */
void   livekit__rtpstats__gap_histogram_entry__init
                     (Livekit__RTPStats__GapHistogramEntry         *message);
/* Livekit__RTPStats methods */
void   livekit__rtpstats__init
                     (Livekit__RTPStats         *message);
size_t livekit__rtpstats__get_packed_size
                     (const Livekit__RTPStats   *message);
size_t livekit__rtpstats__pack
                     (const Livekit__RTPStats   *message,
                      uint8_t             *out);
size_t livekit__rtpstats__pack_to_buffer
                     (const Livekit__RTPStats   *message,
                      ProtobufCBuffer     *buffer);
Livekit__RTPStats *
       livekit__rtpstats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__rtpstats__free_unpacked
                     (Livekit__RTPStats *message,
                      ProtobufCAllocator *allocator);
/* Livekit__RTCPSenderReportState methods */
void   livekit__rtcpsender_report_state__init
                     (Livekit__RTCPSenderReportState         *message);
size_t livekit__rtcpsender_report_state__get_packed_size
                     (const Livekit__RTCPSenderReportState   *message);
size_t livekit__rtcpsender_report_state__pack
                     (const Livekit__RTCPSenderReportState   *message,
                      uint8_t             *out);
size_t livekit__rtcpsender_report_state__pack_to_buffer
                     (const Livekit__RTCPSenderReportState   *message,
                      ProtobufCBuffer     *buffer);
Livekit__RTCPSenderReportState *
       livekit__rtcpsender_report_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__rtcpsender_report_state__free_unpacked
                     (Livekit__RTCPSenderReportState *message,
                      ProtobufCAllocator *allocator);
/* Livekit__RTPForwarderState methods */
void   livekit__rtpforwarder_state__init
                     (Livekit__RTPForwarderState         *message);
size_t livekit__rtpforwarder_state__get_packed_size
                     (const Livekit__RTPForwarderState   *message);
size_t livekit__rtpforwarder_state__pack
                     (const Livekit__RTPForwarderState   *message,
                      uint8_t             *out);
size_t livekit__rtpforwarder_state__pack_to_buffer
                     (const Livekit__RTPForwarderState   *message,
                      ProtobufCBuffer     *buffer);
Livekit__RTPForwarderState *
       livekit__rtpforwarder_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__rtpforwarder_state__free_unpacked
                     (Livekit__RTPForwarderState *message,
                      ProtobufCAllocator *allocator);
/* Livekit__RTPMungerState methods */
void   livekit__rtpmunger_state__init
                     (Livekit__RTPMungerState         *message);
size_t livekit__rtpmunger_state__get_packed_size
                     (const Livekit__RTPMungerState   *message);
size_t livekit__rtpmunger_state__pack
                     (const Livekit__RTPMungerState   *message,
                      uint8_t             *out);
size_t livekit__rtpmunger_state__pack_to_buffer
                     (const Livekit__RTPMungerState   *message,
                      ProtobufCBuffer     *buffer);
Livekit__RTPMungerState *
       livekit__rtpmunger_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__rtpmunger_state__free_unpacked
                     (Livekit__RTPMungerState *message,
                      ProtobufCAllocator *allocator);
/* Livekit__VP8MungerState methods */
void   livekit__vp8_munger_state__init
                     (Livekit__VP8MungerState         *message);
size_t livekit__vp8_munger_state__get_packed_size
                     (const Livekit__VP8MungerState   *message);
size_t livekit__vp8_munger_state__pack
                     (const Livekit__VP8MungerState   *message,
                      uint8_t             *out);
size_t livekit__vp8_munger_state__pack_to_buffer
                     (const Livekit__VP8MungerState   *message,
                      ProtobufCBuffer     *buffer);
Livekit__VP8MungerState *
       livekit__vp8_munger_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__vp8_munger_state__free_unpacked
                     (Livekit__VP8MungerState *message,
                      ProtobufCAllocator *allocator);
/* Livekit__TimedVersion methods */
void   livekit__timed_version__init
                     (Livekit__TimedVersion         *message);
size_t livekit__timed_version__get_packed_size
                     (const Livekit__TimedVersion   *message);
size_t livekit__timed_version__pack
                     (const Livekit__TimedVersion   *message,
                      uint8_t             *out);
size_t livekit__timed_version__pack_to_buffer
                     (const Livekit__TimedVersion   *message,
                      ProtobufCBuffer     *buffer);
Livekit__TimedVersion *
       livekit__timed_version__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__timed_version__free_unpacked
                     (Livekit__TimedVersion *message,
                      ProtobufCAllocator *allocator);
/* Livekit__DataStream__TextHeader methods */
void   livekit__data_stream__text_header__init
                     (Livekit__DataStream__TextHeader         *message);
/* Livekit__DataStream__ByteHeader methods */
void   livekit__data_stream__byte_header__init
                     (Livekit__DataStream__ByteHeader         *message);
/* Livekit__DataStream__Header__AttributesEntry methods */
void   livekit__data_stream__header__attributes_entry__init
                     (Livekit__DataStream__Header__AttributesEntry         *message);
/* Livekit__DataStream__Header methods */
void   livekit__data_stream__header__init
                     (Livekit__DataStream__Header         *message);
/* Livekit__DataStream__Chunk methods */
void   livekit__data_stream__chunk__init
                     (Livekit__DataStream__Chunk         *message);
/* Livekit__DataStream__Trailer__AttributesEntry methods */
void   livekit__data_stream__trailer__attributes_entry__init
                     (Livekit__DataStream__Trailer__AttributesEntry         *message);
/* Livekit__DataStream__Trailer methods */
void   livekit__data_stream__trailer__init
                     (Livekit__DataStream__Trailer         *message);
/* Livekit__DataStream methods */
void   livekit__data_stream__init
                     (Livekit__DataStream         *message);
size_t livekit__data_stream__get_packed_size
                     (const Livekit__DataStream   *message);
size_t livekit__data_stream__pack
                     (const Livekit__DataStream   *message,
                      uint8_t             *out);
size_t livekit__data_stream__pack_to_buffer
                     (const Livekit__DataStream   *message,
                      ProtobufCBuffer     *buffer);
Livekit__DataStream *
       livekit__data_stream__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__data_stream__free_unpacked
                     (Livekit__DataStream *message,
                      ProtobufCAllocator *allocator);
/* Livekit__WebhookConfig methods */
void   livekit__webhook_config__init
                     (Livekit__WebhookConfig         *message);
size_t livekit__webhook_config__get_packed_size
                     (const Livekit__WebhookConfig   *message);
size_t livekit__webhook_config__pack
                     (const Livekit__WebhookConfig   *message,
                      uint8_t             *out);
size_t livekit__webhook_config__pack_to_buffer
                     (const Livekit__WebhookConfig   *message,
                      ProtobufCBuffer     *buffer);
Livekit__WebhookConfig *
       livekit__webhook_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__webhook_config__free_unpacked
                     (Livekit__WebhookConfig *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Livekit__Pagination_Closure)
                 (const Livekit__Pagination *message,
                  void *closure_data);
typedef void (*Livekit__ListUpdate_Closure)
                 (const Livekit__ListUpdate *message,
                  void *closure_data);
typedef void (*Livekit__Room_Closure)
                 (const Livekit__Room *message,
                  void *closure_data);
typedef void (*Livekit__Codec_Closure)
                 (const Livekit__Codec *message,
                  void *closure_data);
typedef void (*Livekit__PlayoutDelay_Closure)
                 (const Livekit__PlayoutDelay *message,
                  void *closure_data);
typedef void (*Livekit__ParticipantPermission_Closure)
                 (const Livekit__ParticipantPermission *message,
                  void *closure_data);
typedef void (*Livekit__ParticipantInfo__AttributesEntry_Closure)
                 (const Livekit__ParticipantInfo__AttributesEntry *message,
                  void *closure_data);
typedef void (*Livekit__ParticipantInfo_Closure)
                 (const Livekit__ParticipantInfo *message,
                  void *closure_data);
typedef void (*Livekit__Encryption_Closure)
                 (const Livekit__Encryption *message,
                  void *closure_data);
typedef void (*Livekit__SimulcastCodecInfo_Closure)
                 (const Livekit__SimulcastCodecInfo *message,
                  void *closure_data);
typedef void (*Livekit__TrackInfo_Closure)
                 (const Livekit__TrackInfo *message,
                  void *closure_data);
typedef void (*Livekit__VideoLayer_Closure)
                 (const Livekit__VideoLayer *message,
                  void *closure_data);
typedef void (*Livekit__DataPacket_Closure)
                 (const Livekit__DataPacket *message,
                  void *closure_data);
typedef void (*Livekit__ActiveSpeakerUpdate_Closure)
                 (const Livekit__ActiveSpeakerUpdate *message,
                  void *closure_data);
typedef void (*Livekit__SpeakerInfo_Closure)
                 (const Livekit__SpeakerInfo *message,
                  void *closure_data);
typedef void (*Livekit__UserPacket_Closure)
                 (const Livekit__UserPacket *message,
                  void *closure_data);
typedef void (*Livekit__SipDTMF_Closure)
                 (const Livekit__SipDTMF *message,
                  void *closure_data);
typedef void (*Livekit__Transcription_Closure)
                 (const Livekit__Transcription *message,
                  void *closure_data);
typedef void (*Livekit__TranscriptionSegment_Closure)
                 (const Livekit__TranscriptionSegment *message,
                  void *closure_data);
typedef void (*Livekit__ChatMessage_Closure)
                 (const Livekit__ChatMessage *message,
                  void *closure_data);
typedef void (*Livekit__RpcRequest_Closure)
                 (const Livekit__RpcRequest *message,
                  void *closure_data);
typedef void (*Livekit__RpcAck_Closure)
                 (const Livekit__RpcAck *message,
                  void *closure_data);
typedef void (*Livekit__RpcResponse_Closure)
                 (const Livekit__RpcResponse *message,
                  void *closure_data);
typedef void (*Livekit__RpcError_Closure)
                 (const Livekit__RpcError *message,
                  void *closure_data);
typedef void (*Livekit__ParticipantTracks_Closure)
                 (const Livekit__ParticipantTracks *message,
                  void *closure_data);
typedef void (*Livekit__ServerInfo_Closure)
                 (const Livekit__ServerInfo *message,
                  void *closure_data);
typedef void (*Livekit__ClientInfo_Closure)
                 (const Livekit__ClientInfo *message,
                  void *closure_data);
typedef void (*Livekit__ClientConfiguration_Closure)
                 (const Livekit__ClientConfiguration *message,
                  void *closure_data);
typedef void (*Livekit__VideoConfiguration_Closure)
                 (const Livekit__VideoConfiguration *message,
                  void *closure_data);
typedef void (*Livekit__DisabledCodecs_Closure)
                 (const Livekit__DisabledCodecs *message,
                  void *closure_data);
typedef void (*Livekit__RTPDrift_Closure)
                 (const Livekit__RTPDrift *message,
                  void *closure_data);
typedef void (*Livekit__RTPStats__GapHistogramEntry_Closure)
                 (const Livekit__RTPStats__GapHistogramEntry *message,
                  void *closure_data);
typedef void (*Livekit__RTPStats_Closure)
                 (const Livekit__RTPStats *message,
                  void *closure_data);
typedef void (*Livekit__RTCPSenderReportState_Closure)
                 (const Livekit__RTCPSenderReportState *message,
                  void *closure_data);
typedef void (*Livekit__RTPForwarderState_Closure)
                 (const Livekit__RTPForwarderState *message,
                  void *closure_data);
typedef void (*Livekit__RTPMungerState_Closure)
                 (const Livekit__RTPMungerState *message,
                  void *closure_data);
typedef void (*Livekit__VP8MungerState_Closure)
                 (const Livekit__VP8MungerState *message,
                  void *closure_data);
typedef void (*Livekit__TimedVersion_Closure)
                 (const Livekit__TimedVersion *message,
                  void *closure_data);
typedef void (*Livekit__DataStream__TextHeader_Closure)
                 (const Livekit__DataStream__TextHeader *message,
                  void *closure_data);
typedef void (*Livekit__DataStream__ByteHeader_Closure)
                 (const Livekit__DataStream__ByteHeader *message,
                  void *closure_data);
typedef void (*Livekit__DataStream__Header__AttributesEntry_Closure)
                 (const Livekit__DataStream__Header__AttributesEntry *message,
                  void *closure_data);
typedef void (*Livekit__DataStream__Header_Closure)
                 (const Livekit__DataStream__Header *message,
                  void *closure_data);
typedef void (*Livekit__DataStream__Chunk_Closure)
                 (const Livekit__DataStream__Chunk *message,
                  void *closure_data);
typedef void (*Livekit__DataStream__Trailer__AttributesEntry_Closure)
                 (const Livekit__DataStream__Trailer__AttributesEntry *message,
                  void *closure_data);
typedef void (*Livekit__DataStream__Trailer_Closure)
                 (const Livekit__DataStream__Trailer *message,
                  void *closure_data);
typedef void (*Livekit__DataStream_Closure)
                 (const Livekit__DataStream *message,
                  void *closure_data);
typedef void (*Livekit__WebhookConfig_Closure)
                 (const Livekit__WebhookConfig *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    livekit__audio_codec__descriptor;
extern const ProtobufCEnumDescriptor    livekit__video_codec__descriptor;
extern const ProtobufCEnumDescriptor    livekit__image_codec__descriptor;
extern const ProtobufCEnumDescriptor    livekit__backup_codec_policy__descriptor;
extern const ProtobufCEnumDescriptor    livekit__track_type__descriptor;
extern const ProtobufCEnumDescriptor    livekit__track_source__descriptor;
extern const ProtobufCEnumDescriptor    livekit__video_quality__descriptor;
extern const ProtobufCEnumDescriptor    livekit__connection_quality__descriptor;
extern const ProtobufCEnumDescriptor    livekit__client_config_setting__descriptor;
extern const ProtobufCEnumDescriptor    livekit__disconnect_reason__descriptor;
extern const ProtobufCEnumDescriptor    livekit__reconnect_reason__descriptor;
extern const ProtobufCEnumDescriptor    livekit__subscription_error__descriptor;
extern const ProtobufCEnumDescriptor    livekit__audio_track_feature__descriptor;
extern const ProtobufCMessageDescriptor livekit__pagination__descriptor;
extern const ProtobufCMessageDescriptor livekit__list_update__descriptor;
extern const ProtobufCMessageDescriptor livekit__room__descriptor;
extern const ProtobufCMessageDescriptor livekit__codec__descriptor;
extern const ProtobufCMessageDescriptor livekit__playout_delay__descriptor;
extern const ProtobufCMessageDescriptor livekit__participant_permission__descriptor;
extern const ProtobufCMessageDescriptor livekit__participant_info__descriptor;
extern const ProtobufCMessageDescriptor livekit__participant_info__attributes_entry__descriptor;
extern const ProtobufCEnumDescriptor    livekit__participant_info__state__descriptor;
extern const ProtobufCEnumDescriptor    livekit__participant_info__kind__descriptor;
extern const ProtobufCEnumDescriptor    livekit__participant_info__kind_detail__descriptor;
extern const ProtobufCMessageDescriptor livekit__encryption__descriptor;
extern const ProtobufCEnumDescriptor    livekit__encryption__type__descriptor;
extern const ProtobufCMessageDescriptor livekit__simulcast_codec_info__descriptor;
extern const ProtobufCMessageDescriptor livekit__track_info__descriptor;
extern const ProtobufCMessageDescriptor livekit__video_layer__descriptor;
extern const ProtobufCMessageDescriptor livekit__data_packet__descriptor;
extern const ProtobufCEnumDescriptor    livekit__data_packet__kind__descriptor;
extern const ProtobufCMessageDescriptor livekit__active_speaker_update__descriptor;
extern const ProtobufCMessageDescriptor livekit__speaker_info__descriptor;
extern const ProtobufCMessageDescriptor livekit__user_packet__descriptor;
extern const ProtobufCMessageDescriptor livekit__sip_dtmf__descriptor;
extern const ProtobufCMessageDescriptor livekit__transcription__descriptor;
extern const ProtobufCMessageDescriptor livekit__transcription_segment__descriptor;
extern const ProtobufCMessageDescriptor livekit__chat_message__descriptor;
extern const ProtobufCMessageDescriptor livekit__rpc_request__descriptor;
extern const ProtobufCMessageDescriptor livekit__rpc_ack__descriptor;
extern const ProtobufCMessageDescriptor livekit__rpc_response__descriptor;
extern const ProtobufCMessageDescriptor livekit__rpc_error__descriptor;
extern const ProtobufCMessageDescriptor livekit__participant_tracks__descriptor;
extern const ProtobufCMessageDescriptor livekit__server_info__descriptor;
extern const ProtobufCEnumDescriptor    livekit__server_info__edition__descriptor;
extern const ProtobufCMessageDescriptor livekit__client_info__descriptor;
extern const ProtobufCEnumDescriptor    livekit__client_info__sdk__descriptor;
extern const ProtobufCMessageDescriptor livekit__client_configuration__descriptor;
extern const ProtobufCMessageDescriptor livekit__video_configuration__descriptor;
extern const ProtobufCMessageDescriptor livekit__disabled_codecs__descriptor;
extern const ProtobufCMessageDescriptor livekit__rtpdrift__descriptor;
extern const ProtobufCMessageDescriptor livekit__rtpstats__descriptor;
extern const ProtobufCMessageDescriptor livekit__rtpstats__gap_histogram_entry__descriptor;
extern const ProtobufCMessageDescriptor livekit__rtcpsender_report_state__descriptor;
extern const ProtobufCMessageDescriptor livekit__rtpforwarder_state__descriptor;
extern const ProtobufCMessageDescriptor livekit__rtpmunger_state__descriptor;
extern const ProtobufCMessageDescriptor livekit__vp8_munger_state__descriptor;
extern const ProtobufCMessageDescriptor livekit__timed_version__descriptor;
extern const ProtobufCMessageDescriptor livekit__data_stream__descriptor;
extern const ProtobufCMessageDescriptor livekit__data_stream__text_header__descriptor;
extern const ProtobufCMessageDescriptor livekit__data_stream__byte_header__descriptor;
extern const ProtobufCMessageDescriptor livekit__data_stream__header__descriptor;
extern const ProtobufCMessageDescriptor livekit__data_stream__header__attributes_entry__descriptor;
extern const ProtobufCMessageDescriptor livekit__data_stream__chunk__descriptor;
extern const ProtobufCMessageDescriptor livekit__data_stream__trailer__descriptor;
extern const ProtobufCMessageDescriptor livekit__data_stream__trailer__attributes_entry__descriptor;
extern const ProtobufCEnumDescriptor    livekit__data_stream__operation_type__descriptor;
extern const ProtobufCMessageDescriptor livekit__webhook_config__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_livekit_5fmodels_2eproto__INCLUDED */
