/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: livekit_rtc.proto */

#ifndef PROTOBUF_C_livekit_5frtc_2eproto__INCLUDED
#define PROTOBUF_C_livekit_5frtc_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "livekit_models.pb-c.h"

typedef struct Livekit__SignalRequest Livekit__SignalRequest;
typedef struct Livekit__SignalResponse Livekit__SignalResponse;
typedef struct Livekit__SimulcastCodec Livekit__SimulcastCodec;
typedef struct Livekit__AddTrackRequest Livekit__AddTrackRequest;
typedef struct Livekit__TrickleRequest Livekit__TrickleRequest;
typedef struct Livekit__MuteTrackRequest Livekit__MuteTrackRequest;
typedef struct Livekit__JoinResponse Livekit__JoinResponse;
typedef struct Livekit__ReconnectResponse Livekit__ReconnectResponse;
typedef struct Livekit__TrackPublishedResponse Livekit__TrackPublishedResponse;
typedef struct Livekit__TrackUnpublishedResponse Livekit__TrackUnpublishedResponse;
typedef struct Livekit__SessionDescription Livekit__SessionDescription;
typedef struct Livekit__ParticipantUpdate Livekit__ParticipantUpdate;
typedef struct Livekit__UpdateSubscription Livekit__UpdateSubscription;
typedef struct Livekit__UpdateTrackSettings Livekit__UpdateTrackSettings;
typedef struct Livekit__UpdateLocalAudioTrack Livekit__UpdateLocalAudioTrack;
typedef struct Livekit__UpdateLocalVideoTrack Livekit__UpdateLocalVideoTrack;
typedef struct Livekit__LeaveRequest Livekit__LeaveRequest;
typedef struct Livekit__UpdateVideoLayers Livekit__UpdateVideoLayers;
typedef struct Livekit__UpdateParticipantMetadata Livekit__UpdateParticipantMetadata;
typedef struct Livekit__UpdateParticipantMetadata__AttributesEntry Livekit__UpdateParticipantMetadata__AttributesEntry;
typedef struct Livekit__ICEServer Livekit__ICEServer;
typedef struct Livekit__SpeakersChanged Livekit__SpeakersChanged;
typedef struct Livekit__RoomUpdate Livekit__RoomUpdate;
typedef struct Livekit__ConnectionQualityInfo Livekit__ConnectionQualityInfo;
typedef struct Livekit__ConnectionQualityUpdate Livekit__ConnectionQualityUpdate;
typedef struct Livekit__StreamStateInfo Livekit__StreamStateInfo;
typedef struct Livekit__StreamStateUpdate Livekit__StreamStateUpdate;
typedef struct Livekit__SubscribedQuality Livekit__SubscribedQuality;
typedef struct Livekit__SubscribedCodec Livekit__SubscribedCodec;
typedef struct Livekit__SubscribedQualityUpdate Livekit__SubscribedQualityUpdate;
typedef struct Livekit__TrackPermission Livekit__TrackPermission;
typedef struct Livekit__SubscriptionPermission Livekit__SubscriptionPermission;
typedef struct Livekit__SubscriptionPermissionUpdate Livekit__SubscriptionPermissionUpdate;
typedef struct Livekit__RoomMovedResponse Livekit__RoomMovedResponse;
typedef struct Livekit__SyncState Livekit__SyncState;
typedef struct Livekit__DataChannelReceiveState Livekit__DataChannelReceiveState;
typedef struct Livekit__DataChannelInfo Livekit__DataChannelInfo;
typedef struct Livekit__SimulateScenario Livekit__SimulateScenario;
typedef struct Livekit__Ping Livekit__Ping;
typedef struct Livekit__Pong Livekit__Pong;
typedef struct Livekit__RegionSettings Livekit__RegionSettings;
typedef struct Livekit__RegionInfo Livekit__RegionInfo;
typedef struct Livekit__SubscriptionResponse Livekit__SubscriptionResponse;
typedef struct Livekit__RequestResponse Livekit__RequestResponse;
typedef struct Livekit__TrackSubscribed Livekit__TrackSubscribed;


/* --- enums --- */

/*
 * indicates action clients should take on receiving this message
 */
typedef enum _Livekit__LeaveRequest__Action {
  /*
   * should disconnect
   */
  LIVEKIT__LEAVE_REQUEST__ACTION__DISCONNECT = 0,
  /*
   * should attempt a resume with `reconnect=1` in join URL
   */
  LIVEKIT__LEAVE_REQUEST__ACTION__RESUME = 1,
  /*
   * should attempt a reconnect, i. e. no `reconnect=1`
   */
  LIVEKIT__LEAVE_REQUEST__ACTION__RECONNECT = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__LEAVE_REQUEST__ACTION)
} Livekit__LeaveRequest__Action;
typedef enum _Livekit__RequestResponse__Reason {
  LIVEKIT__REQUEST_RESPONSE__REASON__OK = 0,
  LIVEKIT__REQUEST_RESPONSE__REASON__NOT_FOUND = 1,
  LIVEKIT__REQUEST_RESPONSE__REASON__NOT_ALLOWED = 2,
  LIVEKIT__REQUEST_RESPONSE__REASON__LIMIT_EXCEEDED = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__REQUEST_RESPONSE__REASON)
} Livekit__RequestResponse__Reason;
typedef enum _Livekit__SignalTarget {
  LIVEKIT__SIGNAL_TARGET__PUBLISHER = 0,
  LIVEKIT__SIGNAL_TARGET__SUBSCRIBER = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__SIGNAL_TARGET)
} Livekit__SignalTarget;
typedef enum _Livekit__StreamState {
  LIVEKIT__STREAM_STATE__ACTIVE = 0,
  LIVEKIT__STREAM_STATE__PAUSED = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__STREAM_STATE)
} Livekit__StreamState;
typedef enum _Livekit__CandidateProtocol {
  LIVEKIT__CANDIDATE_PROTOCOL__UDP = 0,
  LIVEKIT__CANDIDATE_PROTOCOL__TCP = 1,
  LIVEKIT__CANDIDATE_PROTOCOL__TLS = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__CANDIDATE_PROTOCOL)
} Livekit__CandidateProtocol;

/* --- messages --- */

typedef enum {
  LIVEKIT__SIGNAL_REQUEST__MESSAGE__NOT_SET = 0,
  LIVEKIT__SIGNAL_REQUEST__MESSAGE_OFFER = 1,
  LIVEKIT__SIGNAL_REQUEST__MESSAGE_ANSWER = 2,
  LIVEKIT__SIGNAL_REQUEST__MESSAGE_TRICKLE = 3,
  LIVEKIT__SIGNAL_REQUEST__MESSAGE_ADD_TRACK = 4,
  LIVEKIT__SIGNAL_REQUEST__MESSAGE_MUTE = 5,
  LIVEKIT__SIGNAL_REQUEST__MESSAGE_SUBSCRIPTION = 6,
  LIVEKIT__SIGNAL_REQUEST__MESSAGE_TRACK_SETTING = 7,
  LIVEKIT__SIGNAL_REQUEST__MESSAGE_LEAVE = 8,
  LIVEKIT__SIGNAL_REQUEST__MESSAGE_UPDATE_LAYERS = 10,
  LIVEKIT__SIGNAL_REQUEST__MESSAGE_SUBSCRIPTION_PERMISSION = 11,
  LIVEKIT__SIGNAL_REQUEST__MESSAGE_SYNC_STATE = 12,
  LIVEKIT__SIGNAL_REQUEST__MESSAGE_SIMULATE = 13,
  LIVEKIT__SIGNAL_REQUEST__MESSAGE_PING = 14,
  LIVEKIT__SIGNAL_REQUEST__MESSAGE_UPDATE_METADATA = 15,
  LIVEKIT__SIGNAL_REQUEST__MESSAGE_PING_REQ = 16,
  LIVEKIT__SIGNAL_REQUEST__MESSAGE_UPDATE_AUDIO_TRACK = 17,
  LIVEKIT__SIGNAL_REQUEST__MESSAGE_UPDATE_VIDEO_TRACK = 18
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__SIGNAL_REQUEST__MESSAGE__CASE)
} Livekit__SignalRequest__MessageCase;

struct  Livekit__SignalRequest
{
  ProtobufCMessage base;
  Livekit__SignalRequest__MessageCase message_case;
  union {
    /*
     * client triggered ping to server
     */
    /*
     * deprecated by ping_req (message Ping)
     */
    int64_t ping;
    Livekit__AddTrackRequest *add_track;
    /*
     * participant answering publisher offer
     */
    Livekit__SessionDescription *answer;
    /*
     * Immediately terminate session
     */
    Livekit__LeaveRequest *leave;
    /*
     * mute the participant's published tracks
     */
    Livekit__MuteTrackRequest *mute;
    /*
     * initial join exchange, for publisher
     */
    Livekit__SessionDescription *offer;
    Livekit__Ping *ping_req;
    /*
     * Simulate conditions, for client validations
     */
    Livekit__SimulateScenario *simulate;
    /*
     * Subscribe or unsubscribe from tracks
     */
    Livekit__UpdateSubscription *subscription;
    /*
     * Update subscriber permissions
     */
    Livekit__SubscriptionPermission *subscription_permission;
    /*
     * sync client's subscribe state to server during reconnect
     */
    Livekit__SyncState *sync_state;
    /*
     * Update settings of subscribed tracks
     */
    Livekit__UpdateTrackSettings *track_setting;
    Livekit__TrickleRequest *trickle;
    /*
     * Update local audio track settings
     */
    Livekit__UpdateLocalAudioTrack *update_audio_track;
    /*
     * Update published video layers
     */
    Livekit__UpdateVideoLayers *update_layers PROTOBUF_C__DEPRECATED;
    /*
     * update a participant's own metadata, name, or attributes
     * requires canUpdateOwnParticipantMetadata permission
     */
    Livekit__UpdateParticipantMetadata *update_metadata;
    /*
     * Update local video track settings
     */
    Livekit__UpdateLocalVideoTrack *update_video_track;
  };
};
#define LIVEKIT__SIGNAL_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__signal_request__descriptor) \
, LIVEKIT__SIGNAL_REQUEST__MESSAGE__NOT_SET, {0} }


typedef enum {
  LIVEKIT__SIGNAL_RESPONSE__MESSAGE__NOT_SET = 0,
  LIVEKIT__SIGNAL_RESPONSE__MESSAGE_JOIN = 1,
  LIVEKIT__SIGNAL_RESPONSE__MESSAGE_ANSWER = 2,
  LIVEKIT__SIGNAL_RESPONSE__MESSAGE_OFFER = 3,
  LIVEKIT__SIGNAL_RESPONSE__MESSAGE_TRICKLE = 4,
  LIVEKIT__SIGNAL_RESPONSE__MESSAGE_UPDATE = 5,
  LIVEKIT__SIGNAL_RESPONSE__MESSAGE_TRACK_PUBLISHED = 6,
  LIVEKIT__SIGNAL_RESPONSE__MESSAGE_LEAVE = 8,
  LIVEKIT__SIGNAL_RESPONSE__MESSAGE_MUTE = 9,
  LIVEKIT__SIGNAL_RESPONSE__MESSAGE_SPEAKERS_CHANGED = 10,
  LIVEKIT__SIGNAL_RESPONSE__MESSAGE_ROOM_UPDATE = 11,
  LIVEKIT__SIGNAL_RESPONSE__MESSAGE_CONNECTION_QUALITY = 12,
  LIVEKIT__SIGNAL_RESPONSE__MESSAGE_STREAM_STATE_UPDATE = 13,
  LIVEKIT__SIGNAL_RESPONSE__MESSAGE_SUBSCRIBED_QUALITY_UPDATE = 14,
  LIVEKIT__SIGNAL_RESPONSE__MESSAGE_SUBSCRIPTION_PERMISSION_UPDATE = 15,
  LIVEKIT__SIGNAL_RESPONSE__MESSAGE_REFRESH_TOKEN = 16,
  LIVEKIT__SIGNAL_RESPONSE__MESSAGE_TRACK_UNPUBLISHED = 17,
  LIVEKIT__SIGNAL_RESPONSE__MESSAGE_PONG = 18,
  LIVEKIT__SIGNAL_RESPONSE__MESSAGE_RECONNECT = 19,
  LIVEKIT__SIGNAL_RESPONSE__MESSAGE_PONG_RESP = 20,
  LIVEKIT__SIGNAL_RESPONSE__MESSAGE_SUBSCRIPTION_RESPONSE = 21,
  LIVEKIT__SIGNAL_RESPONSE__MESSAGE_REQUEST_RESPONSE = 22,
  LIVEKIT__SIGNAL_RESPONSE__MESSAGE_TRACK_SUBSCRIBED = 23,
  LIVEKIT__SIGNAL_RESPONSE__MESSAGE_ROOM_MOVED = 24
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__SIGNAL_RESPONSE__MESSAGE__CASE)
} Livekit__SignalResponse__MessageCase;

struct  Livekit__SignalResponse
{
  ProtobufCMessage base;
  Livekit__SignalResponse__MessageCase message_case;
  union {
    /*
     * respond to ping
     */
    /*
     * deprecated by pong_resp (message Pong)
     */
    int64_t pong;
    /*
     * update the token the client was using, to prevent an active client from using an expired token
     */
    char *refresh_token;
    /*
     * sent when server answers publisher
     */
    Livekit__SessionDescription *answer;
    /*
     * when connection quality changed
     */
    Livekit__ConnectionQualityUpdate *connection_quality;
    /*
     * sent when join is accepted
     */
    Livekit__JoinResponse *join;
    /*
     * Immediately terminate session
     */
    Livekit__LeaveRequest *leave;
    /*
     * server initiated mute
     */
    Livekit__MuteTrackRequest *mute;
    /*
     * sent when server is sending subscriber an offer
     */
    Livekit__SessionDescription *offer;
    /*
     * respond to Ping
     */
    Livekit__Pong *pong_resp;
    /*
     * sent when client reconnects
     */
    Livekit__ReconnectResponse *reconnect;
    /*
     * Response relating to user inititated requests that carry a `request_id`
     */
    Livekit__RequestResponse *request_response;
    /*
     * notify to the participant when they have been moved to a new room
     */
    Livekit__RoomMovedResponse *room_moved;
    /*
     * sent when metadata of the room has changed
     */
    Livekit__RoomUpdate *room_update;
    /*
     * indicates changes to speaker status, including when they've gone to not speaking
     */
    Livekit__SpeakersChanged *speakers_changed;
    /*
     * when streamed tracks state changed, used to notify when any of the streams were paused due to
     * congestion
     */
    Livekit__StreamStateUpdate *stream_state_update;
    /*
     * when max subscribe quality changed, used by dynamic broadcasting to disable unused layers
     */
    Livekit__SubscribedQualityUpdate *subscribed_quality_update;
    /*
     * when subscription permission changed
     */
    Livekit__SubscriptionPermissionUpdate *subscription_permission_update;
    /*
     * Subscription response, client should not expect any media from this subscription if it fails
     */
    Livekit__SubscriptionResponse *subscription_response;
    /*
     * sent to the participant when their track has been published
     */
    Livekit__TrackPublishedResponse *track_published;
    /*
     * notify to the publisher when a published track has been subscribed for the first time
     */
    Livekit__TrackSubscribed *track_subscribed;
    /*
     * server initiated track unpublish
     */
    Livekit__TrackUnpublishedResponse *track_unpublished;
    /*
     * sent when an ICE candidate is available
     */
    Livekit__TrickleRequest *trickle;
    /*
     * sent when participants in the room has changed
     */
    Livekit__ParticipantUpdate *update;
  };
};
#define LIVEKIT__SIGNAL_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__signal_response__descriptor) \
, LIVEKIT__SIGNAL_RESPONSE__MESSAGE__NOT_SET, {0} }


struct  Livekit__SimulcastCodec
{
  ProtobufCMessage base;
  char *codec;
  char *cid;
};
#define LIVEKIT__SIMULCAST_CODEC__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__simulcast_codec__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Livekit__AddTrackRequest
{
  ProtobufCMessage base;
  /*
   * client ID of track, to match it when RTC track is received
   */
  char *cid;
  char *name;
  Livekit__TrackType type;
  /*
   * to be deprecated in favor of layers
   */
  uint32_t width;
  uint32_t height;
  /*
   * true to add track and initialize to muted
   */
  protobuf_c_boolean muted;
  /*
   * true if DTX (Discontinuous Transmission) is disabled for audio
   */
  /*
   * deprecated in favor of audio_features
   */
  protobuf_c_boolean disable_dtx PROTOBUF_C__DEPRECATED;
  Livekit__TrackSource source;
  size_t n_layers;
  Livekit__VideoLayer **layers;
  size_t n_simulcast_codecs;
  Livekit__SimulcastCodec **simulcast_codecs;
  /*
   * server ID of track, publish new codec to exist track
   */
  char *sid;
  /*
   * deprecated in favor of audio_features
   */
  protobuf_c_boolean stereo PROTOBUF_C__DEPRECATED;
  /*
   * true if RED (Redundant Encoding) is disabled for audio
   */
  protobuf_c_boolean disable_red;
  Livekit__Encryption__Type encryption;
  /*
   * which stream the track belongs to, used to group tracks together.
   * if not specified, server will infer it from track source to bundle camera/microphone, screenshare/audio together
   */
  char *stream;
  Livekit__BackupCodecPolicy backup_codec_policy;
  size_t n_audio_features;
  Livekit__AudioTrackFeature *audio_features;
};
#define LIVEKIT__ADD_TRACK_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__add_track_request__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, LIVEKIT__TRACK_TYPE__AUDIO, 0, 0, 0, 0, LIVEKIT__TRACK_SOURCE__UNKNOWN, 0,NULL, 0,NULL, (char *)protobuf_c_empty_string, 0, 0, LIVEKIT__ENCRYPTION__TYPE__NONE, (char *)protobuf_c_empty_string, LIVEKIT__BACKUP_CODEC_POLICY__PREFER_REGRESSION, 0,NULL }


struct  Livekit__TrickleRequest
{
  ProtobufCMessage base;
  char *candidateinit;
  Livekit__SignalTarget target;
  protobuf_c_boolean final;
};
#define LIVEKIT__TRICKLE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__trickle_request__descriptor) \
, (char *)protobuf_c_empty_string, LIVEKIT__SIGNAL_TARGET__PUBLISHER, 0 }


struct  Livekit__MuteTrackRequest
{
  ProtobufCMessage base;
  char *sid;
  protobuf_c_boolean muted;
};
#define LIVEKIT__MUTE_TRACK_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__mute_track_request__descriptor) \
, (char *)protobuf_c_empty_string, 0 }


struct  Livekit__JoinResponse
{
  ProtobufCMessage base;
  Livekit__Room *room;
  Livekit__ParticipantInfo *participant;
  size_t n_other_participants;
  Livekit__ParticipantInfo **other_participants;
  /*
   * deprecated. use server_info.version instead.
   */
  char *server_version;
  size_t n_ice_servers;
  Livekit__ICEServer **ice_servers;
  /*
   * use subscriber as the primary PeerConnection
   */
  protobuf_c_boolean subscriber_primary;
  /*
   * when the current server isn't available, return alternate url to retry connection
   * when this is set, the other fields will be largely empty
   */
  char *alternative_url;
  Livekit__ClientConfiguration *client_configuration;
  /*
   * deprecated. use server_info.region instead.
   */
  char *server_region;
  int32_t ping_timeout;
  int32_t ping_interval;
  Livekit__ServerInfo *server_info;
  /*
   * Server-Injected-Frame byte trailer, used to identify unencrypted frames when e2ee is enabled
   */
  ProtobufCBinaryData sif_trailer;
  size_t n_enabled_publish_codecs;
  Livekit__Codec **enabled_publish_codecs;
  /*
   * when set, client should attempt to establish publish peer connection when joining room to speed up publishing
   */
  protobuf_c_boolean fast_publish;
};
#define LIVEKIT__JOIN_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__join_response__descriptor) \
, NULL, NULL, 0,NULL, (char *)protobuf_c_empty_string, 0,NULL, 0, (char *)protobuf_c_empty_string, NULL, (char *)protobuf_c_empty_string, 0, 0, NULL, {0,NULL}, 0,NULL, 0 }


struct  Livekit__ReconnectResponse
{
  ProtobufCMessage base;
  size_t n_ice_servers;
  Livekit__ICEServer **ice_servers;
  Livekit__ClientConfiguration *client_configuration;
  Livekit__ServerInfo *server_info;
  /*
   * last sequence number of reliable message received before resuming
   */
  uint32_t last_message_seq;
};
#define LIVEKIT__RECONNECT_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__reconnect_response__descriptor) \
, 0,NULL, NULL, NULL, 0 }


struct  Livekit__TrackPublishedResponse
{
  ProtobufCMessage base;
  char *cid;
  Livekit__TrackInfo *track;
};
#define LIVEKIT__TRACK_PUBLISHED_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__track_published_response__descriptor) \
, (char *)protobuf_c_empty_string, NULL }


struct  Livekit__TrackUnpublishedResponse
{
  ProtobufCMessage base;
  char *track_sid;
};
#define LIVEKIT__TRACK_UNPUBLISHED_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__track_unpublished_response__descriptor) \
, (char *)protobuf_c_empty_string }


struct  Livekit__SessionDescription
{
  ProtobufCMessage base;
  /*
   * "answer" | "offer" | "pranswer" | "rollback"
   */
  char *type;
  char *sdp;
  uint32_t id;
};
#define LIVEKIT__SESSION_DESCRIPTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__session_description__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


struct  Livekit__ParticipantUpdate
{
  ProtobufCMessage base;
  size_t n_participants;
  Livekit__ParticipantInfo **participants;
};
#define LIVEKIT__PARTICIPANT_UPDATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__participant_update__descriptor) \
, 0,NULL }


struct  Livekit__UpdateSubscription
{
  ProtobufCMessage base;
  size_t n_track_sids;
  char **track_sids;
  protobuf_c_boolean subscribe;
  size_t n_participant_tracks;
  Livekit__ParticipantTracks **participant_tracks;
};
#define LIVEKIT__UPDATE_SUBSCRIPTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__update_subscription__descriptor) \
, 0,NULL, 0, 0,NULL }


struct  Livekit__UpdateTrackSettings
{
  ProtobufCMessage base;
  size_t n_track_sids;
  char **track_sids;
  /*
   * when true, the track is placed in a paused state, with no new data returned
   */
  protobuf_c_boolean disabled;
  /*
   * deprecated in favor of width & height
   */
  Livekit__VideoQuality quality;
  /*
   * for video, width to receive
   */
  uint32_t width;
  /*
   * for video, height to receive
   */
  uint32_t height;
  uint32_t fps;
  /*
   * subscription priority. 1 being the highest (0 is unset)
   * when unset, server sill assign priority based on the order of subscription
   * server will use priority in the following ways:
   * 1. when subscribed tracks exceed per-participant subscription limit, server will
   *    pause the lowest priority tracks
   * 2. when the network is congested, server will assign available bandwidth to
   *    higher priority tracks first. lowest priority tracks can be paused
   */
  uint32_t priority;
};
#define LIVEKIT__UPDATE_TRACK_SETTINGS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__update_track_settings__descriptor) \
, 0,NULL, 0, LIVEKIT__VIDEO_QUALITY__LOW, 0, 0, 0, 0 }


struct  Livekit__UpdateLocalAudioTrack
{
  ProtobufCMessage base;
  char *track_sid;
  size_t n_features;
  Livekit__AudioTrackFeature *features;
};
#define LIVEKIT__UPDATE_LOCAL_AUDIO_TRACK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__update_local_audio_track__descriptor) \
, (char *)protobuf_c_empty_string, 0,NULL }


struct  Livekit__UpdateLocalVideoTrack
{
  ProtobufCMessage base;
  char *track_sid;
  uint32_t width;
  uint32_t height;
};
#define LIVEKIT__UPDATE_LOCAL_VIDEO_TRACK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__update_local_video_track__descriptor) \
, (char *)protobuf_c_empty_string, 0, 0 }


struct  Livekit__LeaveRequest
{
  ProtobufCMessage base;
  /*
   * sent when server initiates the disconnect due to server-restart
   * indicates clients should attempt full-reconnect sequence
   * NOTE: `can_reconnect` obsoleted by `action` starting in protocol version 13
   */
  protobuf_c_boolean can_reconnect;
  Livekit__DisconnectReason reason;
  Livekit__LeaveRequest__Action action;
  Livekit__RegionSettings *regions;
};
#define LIVEKIT__LEAVE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__leave_request__descriptor) \
, 0, LIVEKIT__DISCONNECT_REASON__UNKNOWN_REASON, LIVEKIT__LEAVE_REQUEST__ACTION__DISCONNECT, NULL }


/*
 * message to indicate published video track dimensions are changing
 */
struct  Livekit__UpdateVideoLayers
{
  ProtobufCMessage base;
  char *track_sid;
  size_t n_layers;
  Livekit__VideoLayer **layers;
};
#define LIVEKIT__UPDATE_VIDEO_LAYERS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__update_video_layers__descriptor) \
, (char *)protobuf_c_empty_string, 0,NULL }


struct  Livekit__UpdateParticipantMetadata__AttributesEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define LIVEKIT__UPDATE_PARTICIPANT_METADATA__ATTRIBUTES_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__update_participant_metadata__attributes_entry__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Livekit__UpdateParticipantMetadata
{
  ProtobufCMessage base;
  char *metadata;
  char *name;
  /*
   * attributes to update. it only updates attributes that have been set
   * to delete attributes, set the value to an empty string
   */
  size_t n_attributes;
  Livekit__UpdateParticipantMetadata__AttributesEntry **attributes;
  uint32_t request_id;
};
#define LIVEKIT__UPDATE_PARTICIPANT_METADATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__update_participant_metadata__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL, 0 }


struct  Livekit__ICEServer
{
  ProtobufCMessage base;
  size_t n_urls;
  char **urls;
  char *username;
  char *credential;
};
#define LIVEKIT__ICESERVER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__iceserver__descriptor) \
, 0,NULL, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Livekit__SpeakersChanged
{
  ProtobufCMessage base;
  size_t n_speakers;
  Livekit__SpeakerInfo **speakers;
};
#define LIVEKIT__SPEAKERS_CHANGED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__speakers_changed__descriptor) \
, 0,NULL }


struct  Livekit__RoomUpdate
{
  ProtobufCMessage base;
  Livekit__Room *room;
};
#define LIVEKIT__ROOM_UPDATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__room_update__descriptor) \
, NULL }


struct  Livekit__ConnectionQualityInfo
{
  ProtobufCMessage base;
  char *participant_sid;
  Livekit__ConnectionQuality quality;
  float score;
};
#define LIVEKIT__CONNECTION_QUALITY_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__connection_quality_info__descriptor) \
, (char *)protobuf_c_empty_string, LIVEKIT__CONNECTION_QUALITY__POOR, 0 }


struct  Livekit__ConnectionQualityUpdate
{
  ProtobufCMessage base;
  size_t n_updates;
  Livekit__ConnectionQualityInfo **updates;
};
#define LIVEKIT__CONNECTION_QUALITY_UPDATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__connection_quality_update__descriptor) \
, 0,NULL }


struct  Livekit__StreamStateInfo
{
  ProtobufCMessage base;
  char *participant_sid;
  char *track_sid;
  Livekit__StreamState state;
};
#define LIVEKIT__STREAM_STATE_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__stream_state_info__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, LIVEKIT__STREAM_STATE__ACTIVE }


struct  Livekit__StreamStateUpdate
{
  ProtobufCMessage base;
  size_t n_stream_states;
  Livekit__StreamStateInfo **stream_states;
};
#define LIVEKIT__STREAM_STATE_UPDATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__stream_state_update__descriptor) \
, 0,NULL }


struct  Livekit__SubscribedQuality
{
  ProtobufCMessage base;
  Livekit__VideoQuality quality;
  protobuf_c_boolean enabled;
};
#define LIVEKIT__SUBSCRIBED_QUALITY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__subscribed_quality__descriptor) \
, LIVEKIT__VIDEO_QUALITY__LOW, 0 }


struct  Livekit__SubscribedCodec
{
  ProtobufCMessage base;
  char *codec;
  size_t n_qualities;
  Livekit__SubscribedQuality **qualities;
};
#define LIVEKIT__SUBSCRIBED_CODEC__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__subscribed_codec__descriptor) \
, (char *)protobuf_c_empty_string, 0,NULL }


struct  Livekit__SubscribedQualityUpdate
{
  ProtobufCMessage base;
  char *track_sid;
  size_t n_subscribed_qualities PROTOBUF_C__DEPRECATED;
  Livekit__SubscribedQuality **subscribed_qualities PROTOBUF_C__DEPRECATED;
  size_t n_subscribed_codecs;
  Livekit__SubscribedCodec **subscribed_codecs;
};
#define LIVEKIT__SUBSCRIBED_QUALITY_UPDATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__subscribed_quality_update__descriptor) \
, (char *)protobuf_c_empty_string, 0,NULL, 0,NULL }


struct  Livekit__TrackPermission
{
  ProtobufCMessage base;
  /*
   * permission could be granted either by participant sid or identity
   */
  char *participant_sid;
  protobuf_c_boolean all_tracks;
  size_t n_track_sids;
  char **track_sids;
  char *participant_identity;
};
#define LIVEKIT__TRACK_PERMISSION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__track_permission__descriptor) \
, (char *)protobuf_c_empty_string, 0, 0,NULL, (char *)protobuf_c_empty_string }


struct  Livekit__SubscriptionPermission
{
  ProtobufCMessage base;
  protobuf_c_boolean all_participants;
  size_t n_track_permissions;
  Livekit__TrackPermission **track_permissions;
};
#define LIVEKIT__SUBSCRIPTION_PERMISSION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__subscription_permission__descriptor) \
, 0, 0,NULL }


struct  Livekit__SubscriptionPermissionUpdate
{
  ProtobufCMessage base;
  char *participant_sid;
  char *track_sid;
  protobuf_c_boolean allowed;
};
#define LIVEKIT__SUBSCRIPTION_PERMISSION_UPDATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__subscription_permission_update__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


struct  Livekit__RoomMovedResponse
{
  ProtobufCMessage base;
  /*
   * information about the new room
   */
  Livekit__Room *room;
  /*
   * new reconnect token that can be used to reconnect to the new room
   */
  char *token;
  Livekit__ParticipantInfo *participant;
  size_t n_other_participants;
  Livekit__ParticipantInfo **other_participants;
};
#define LIVEKIT__ROOM_MOVED_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__room_moved_response__descriptor) \
, NULL, (char *)protobuf_c_empty_string, NULL, 0,NULL }


struct  Livekit__SyncState
{
  ProtobufCMessage base;
  /*
   * last subscribe answer before reconnecting
   */
  Livekit__SessionDescription *answer;
  Livekit__UpdateSubscription *subscription;
  size_t n_publish_tracks;
  Livekit__TrackPublishedResponse **publish_tracks;
  size_t n_data_channels;
  Livekit__DataChannelInfo **data_channels;
  /*
   * last received server side offer before reconnecting
   */
  Livekit__SessionDescription *offer;
  size_t n_track_sids_disabled;
  char **track_sids_disabled;
  size_t n_datachannel_receive_states;
  Livekit__DataChannelReceiveState **datachannel_receive_states;
};
#define LIVEKIT__SYNC_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__sync_state__descriptor) \
, NULL, NULL, 0,NULL, 0,NULL, NULL, 0,NULL, 0,NULL }


struct  Livekit__DataChannelReceiveState
{
  ProtobufCMessage base;
  char *publisher_sid;
  uint32_t last_seq;
};
#define LIVEKIT__DATA_CHANNEL_RECEIVE_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__data_channel_receive_state__descriptor) \
, (char *)protobuf_c_empty_string, 0 }


struct  Livekit__DataChannelInfo
{
  ProtobufCMessage base;
  char *label;
  uint32_t id;
  Livekit__SignalTarget target;
};
#define LIVEKIT__DATA_CHANNEL_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__data_channel_info__descriptor) \
, (char *)protobuf_c_empty_string, 0, LIVEKIT__SIGNAL_TARGET__PUBLISHER }


typedef enum {
  LIVEKIT__SIMULATE_SCENARIO__SCENARIO__NOT_SET = 0,
  LIVEKIT__SIMULATE_SCENARIO__SCENARIO_SPEAKER_UPDATE = 1,
  LIVEKIT__SIMULATE_SCENARIO__SCENARIO_NODE_FAILURE = 2,
  LIVEKIT__SIMULATE_SCENARIO__SCENARIO_MIGRATION = 3,
  LIVEKIT__SIMULATE_SCENARIO__SCENARIO_SERVER_LEAVE = 4,
  LIVEKIT__SIMULATE_SCENARIO__SCENARIO_SWITCH_CANDIDATE_PROTOCOL = 5,
  LIVEKIT__SIMULATE_SCENARIO__SCENARIO_SUBSCRIBER_BANDWIDTH = 6,
  LIVEKIT__SIMULATE_SCENARIO__SCENARIO_DISCONNECT_SIGNAL_ON_RESUME = 7,
  LIVEKIT__SIMULATE_SCENARIO__SCENARIO_DISCONNECT_SIGNAL_ON_RESUME_NO_MESSAGES = 8,
  LIVEKIT__SIMULATE_SCENARIO__SCENARIO_LEAVE_REQUEST_FULL_RECONNECT = 9
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__SIMULATE_SCENARIO__SCENARIO__CASE)
} Livekit__SimulateScenario__ScenarioCase;

struct  Livekit__SimulateScenario
{
  ProtobufCMessage base;
  Livekit__SimulateScenario__ScenarioCase scenario_case;
  union {
    /*
     * maximum bandwidth for subscribers, in bps
     * when zero, clears artificial bandwidth limit
     */
    int64_t subscriber_bandwidth;
    /*
     * simulate N seconds of speaker activity
     */
    int32_t speaker_update;
    /*
     * switch candidate protocol to tcp
     */
    Livekit__CandidateProtocol switch_candidate_protocol;
    /*
     * disconnect signal on resume
     */
    protobuf_c_boolean disconnect_signal_on_resume;
    /*
     * disconnect signal on resume before sending any messages from server
     */
    protobuf_c_boolean disconnect_signal_on_resume_no_messages;
    /*
     * full reconnect leave request
     */
    protobuf_c_boolean leave_request_full_reconnect;
    /*
     * simulate migration
     */
    protobuf_c_boolean migration;
    /*
     * simulate local node failure
     */
    protobuf_c_boolean node_failure;
    /*
     * server to send leave
     */
    protobuf_c_boolean server_leave;
  };
};
#define LIVEKIT__SIMULATE_SCENARIO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__simulate_scenario__descriptor) \
, LIVEKIT__SIMULATE_SCENARIO__SCENARIO__NOT_SET, {0} }


struct  Livekit__Ping
{
  ProtobufCMessage base;
  int64_t timestamp;
  /*
   * rtt in milliseconds calculated by client
   */
  int64_t rtt;
};
#define LIVEKIT__PING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__ping__descriptor) \
, 0, 0 }


struct  Livekit__Pong
{
  ProtobufCMessage base;
  /*
   * timestamp field of last received ping request
   */
  int64_t last_ping_timestamp;
  int64_t timestamp;
};
#define LIVEKIT__PONG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__pong__descriptor) \
, 0, 0 }


struct  Livekit__RegionSettings
{
  ProtobufCMessage base;
  size_t n_regions;
  Livekit__RegionInfo **regions;
};
#define LIVEKIT__REGION_SETTINGS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__region_settings__descriptor) \
, 0,NULL }


struct  Livekit__RegionInfo
{
  ProtobufCMessage base;
  char *region;
  char *url;
  int64_t distance;
};
#define LIVEKIT__REGION_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__region_info__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


struct  Livekit__SubscriptionResponse
{
  ProtobufCMessage base;
  char *track_sid;
  Livekit__SubscriptionError err;
};
#define LIVEKIT__SUBSCRIPTION_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__subscription_response__descriptor) \
, (char *)protobuf_c_empty_string, LIVEKIT__SUBSCRIPTION_ERROR__SE_UNKNOWN }


struct  Livekit__RequestResponse
{
  ProtobufCMessage base;
  uint32_t request_id;
  Livekit__RequestResponse__Reason reason;
  char *message;
};
#define LIVEKIT__REQUEST_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__request_response__descriptor) \
, 0, LIVEKIT__REQUEST_RESPONSE__REASON__OK, (char *)protobuf_c_empty_string }


struct  Livekit__TrackSubscribed
{
  ProtobufCMessage base;
  char *track_sid;
};
#define LIVEKIT__TRACK_SUBSCRIBED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__track_subscribed__descriptor) \
, (char *)protobuf_c_empty_string }


/* Livekit__SignalRequest methods */
void   livekit__signal_request__init
                     (Livekit__SignalRequest         *message);
size_t livekit__signal_request__get_packed_size
                     (const Livekit__SignalRequest   *message);
size_t livekit__signal_request__pack
                     (const Livekit__SignalRequest   *message,
                      uint8_t             *out);
size_t livekit__signal_request__pack_to_buffer
                     (const Livekit__SignalRequest   *message,
                      ProtobufCBuffer     *buffer);
Livekit__SignalRequest *
       livekit__signal_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__signal_request__free_unpacked
                     (Livekit__SignalRequest *message,
                      ProtobufCAllocator *allocator);
/* Livekit__SignalResponse methods */
void   livekit__signal_response__init
                     (Livekit__SignalResponse         *message);
size_t livekit__signal_response__get_packed_size
                     (const Livekit__SignalResponse   *message);
size_t livekit__signal_response__pack
                     (const Livekit__SignalResponse   *message,
                      uint8_t             *out);
size_t livekit__signal_response__pack_to_buffer
                     (const Livekit__SignalResponse   *message,
                      ProtobufCBuffer     *buffer);
Livekit__SignalResponse *
       livekit__signal_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__signal_response__free_unpacked
                     (Livekit__SignalResponse *message,
                      ProtobufCAllocator *allocator);
/* Livekit__SimulcastCodec methods */
void   livekit__simulcast_codec__init
                     (Livekit__SimulcastCodec         *message);
size_t livekit__simulcast_codec__get_packed_size
                     (const Livekit__SimulcastCodec   *message);
size_t livekit__simulcast_codec__pack
                     (const Livekit__SimulcastCodec   *message,
                      uint8_t             *out);
size_t livekit__simulcast_codec__pack_to_buffer
                     (const Livekit__SimulcastCodec   *message,
                      ProtobufCBuffer     *buffer);
Livekit__SimulcastCodec *
       livekit__simulcast_codec__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__simulcast_codec__free_unpacked
                     (Livekit__SimulcastCodec *message,
                      ProtobufCAllocator *allocator);
/* Livekit__AddTrackRequest methods */
void   livekit__add_track_request__init
                     (Livekit__AddTrackRequest         *message);
size_t livekit__add_track_request__get_packed_size
                     (const Livekit__AddTrackRequest   *message);
size_t livekit__add_track_request__pack
                     (const Livekit__AddTrackRequest   *message,
                      uint8_t             *out);
size_t livekit__add_track_request__pack_to_buffer
                     (const Livekit__AddTrackRequest   *message,
                      ProtobufCBuffer     *buffer);
Livekit__AddTrackRequest *
       livekit__add_track_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__add_track_request__free_unpacked
                     (Livekit__AddTrackRequest *message,
                      ProtobufCAllocator *allocator);
/* Livekit__TrickleRequest methods */
void   livekit__trickle_request__init
                     (Livekit__TrickleRequest         *message);
size_t livekit__trickle_request__get_packed_size
                     (const Livekit__TrickleRequest   *message);
size_t livekit__trickle_request__pack
                     (const Livekit__TrickleRequest   *message,
                      uint8_t             *out);
size_t livekit__trickle_request__pack_to_buffer
                     (const Livekit__TrickleRequest   *message,
                      ProtobufCBuffer     *buffer);
Livekit__TrickleRequest *
       livekit__trickle_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__trickle_request__free_unpacked
                     (Livekit__TrickleRequest *message,
                      ProtobufCAllocator *allocator);
/* Livekit__MuteTrackRequest methods */
void   livekit__mute_track_request__init
                     (Livekit__MuteTrackRequest         *message);
size_t livekit__mute_track_request__get_packed_size
                     (const Livekit__MuteTrackRequest   *message);
size_t livekit__mute_track_request__pack
                     (const Livekit__MuteTrackRequest   *message,
                      uint8_t             *out);
size_t livekit__mute_track_request__pack_to_buffer
                     (const Livekit__MuteTrackRequest   *message,
                      ProtobufCBuffer     *buffer);
Livekit__MuteTrackRequest *
       livekit__mute_track_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__mute_track_request__free_unpacked
                     (Livekit__MuteTrackRequest *message,
                      ProtobufCAllocator *allocator);
/* Livekit__JoinResponse methods */
void   livekit__join_response__init
                     (Livekit__JoinResponse         *message);
size_t livekit__join_response__get_packed_size
                     (const Livekit__JoinResponse   *message);
size_t livekit__join_response__pack
                     (const Livekit__JoinResponse   *message,
                      uint8_t             *out);
size_t livekit__join_response__pack_to_buffer
                     (const Livekit__JoinResponse   *message,
                      ProtobufCBuffer     *buffer);
Livekit__JoinResponse *
       livekit__join_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__join_response__free_unpacked
                     (Livekit__JoinResponse *message,
                      ProtobufCAllocator *allocator);
/* Livekit__ReconnectResponse methods */
void   livekit__reconnect_response__init
                     (Livekit__ReconnectResponse         *message);
size_t livekit__reconnect_response__get_packed_size
                     (const Livekit__ReconnectResponse   *message);
size_t livekit__reconnect_response__pack
                     (const Livekit__ReconnectResponse   *message,
                      uint8_t             *out);
size_t livekit__reconnect_response__pack_to_buffer
                     (const Livekit__ReconnectResponse   *message,
                      ProtobufCBuffer     *buffer);
Livekit__ReconnectResponse *
       livekit__reconnect_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__reconnect_response__free_unpacked
                     (Livekit__ReconnectResponse *message,
                      ProtobufCAllocator *allocator);
/* Livekit__TrackPublishedResponse methods */
void   livekit__track_published_response__init
                     (Livekit__TrackPublishedResponse         *message);
size_t livekit__track_published_response__get_packed_size
                     (const Livekit__TrackPublishedResponse   *message);
size_t livekit__track_published_response__pack
                     (const Livekit__TrackPublishedResponse   *message,
                      uint8_t             *out);
size_t livekit__track_published_response__pack_to_buffer
                     (const Livekit__TrackPublishedResponse   *message,
                      ProtobufCBuffer     *buffer);
Livekit__TrackPublishedResponse *
       livekit__track_published_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__track_published_response__free_unpacked
                     (Livekit__TrackPublishedResponse *message,
                      ProtobufCAllocator *allocator);
/* Livekit__TrackUnpublishedResponse methods */
void   livekit__track_unpublished_response__init
                     (Livekit__TrackUnpublishedResponse         *message);
size_t livekit__track_unpublished_response__get_packed_size
                     (const Livekit__TrackUnpublishedResponse   *message);
size_t livekit__track_unpublished_response__pack
                     (const Livekit__TrackUnpublishedResponse   *message,
                      uint8_t             *out);
size_t livekit__track_unpublished_response__pack_to_buffer
                     (const Livekit__TrackUnpublishedResponse   *message,
                      ProtobufCBuffer     *buffer);
Livekit__TrackUnpublishedResponse *
       livekit__track_unpublished_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__track_unpublished_response__free_unpacked
                     (Livekit__TrackUnpublishedResponse *message,
                      ProtobufCAllocator *allocator);
/* Livekit__SessionDescription methods */
void   livekit__session_description__init
                     (Livekit__SessionDescription         *message);
size_t livekit__session_description__get_packed_size
                     (const Livekit__SessionDescription   *message);
size_t livekit__session_description__pack
                     (const Livekit__SessionDescription   *message,
                      uint8_t             *out);
size_t livekit__session_description__pack_to_buffer
                     (const Livekit__SessionDescription   *message,
                      ProtobufCBuffer     *buffer);
Livekit__SessionDescription *
       livekit__session_description__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__session_description__free_unpacked
                     (Livekit__SessionDescription *message,
                      ProtobufCAllocator *allocator);
/* Livekit__ParticipantUpdate methods */
void   livekit__participant_update__init
                     (Livekit__ParticipantUpdate         *message);
size_t livekit__participant_update__get_packed_size
                     (const Livekit__ParticipantUpdate   *message);
size_t livekit__participant_update__pack
                     (const Livekit__ParticipantUpdate   *message,
                      uint8_t             *out);
size_t livekit__participant_update__pack_to_buffer
                     (const Livekit__ParticipantUpdate   *message,
                      ProtobufCBuffer     *buffer);
Livekit__ParticipantUpdate *
       livekit__participant_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__participant_update__free_unpacked
                     (Livekit__ParticipantUpdate *message,
                      ProtobufCAllocator *allocator);
/* Livekit__UpdateSubscription methods */
void   livekit__update_subscription__init
                     (Livekit__UpdateSubscription         *message);
size_t livekit__update_subscription__get_packed_size
                     (const Livekit__UpdateSubscription   *message);
size_t livekit__update_subscription__pack
                     (const Livekit__UpdateSubscription   *message,
                      uint8_t             *out);
size_t livekit__update_subscription__pack_to_buffer
                     (const Livekit__UpdateSubscription   *message,
                      ProtobufCBuffer     *buffer);
Livekit__UpdateSubscription *
       livekit__update_subscription__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__update_subscription__free_unpacked
                     (Livekit__UpdateSubscription *message,
                      ProtobufCAllocator *allocator);
/* Livekit__UpdateTrackSettings methods */
void   livekit__update_track_settings__init
                     (Livekit__UpdateTrackSettings         *message);
size_t livekit__update_track_settings__get_packed_size
                     (const Livekit__UpdateTrackSettings   *message);
size_t livekit__update_track_settings__pack
                     (const Livekit__UpdateTrackSettings   *message,
                      uint8_t             *out);
size_t livekit__update_track_settings__pack_to_buffer
                     (const Livekit__UpdateTrackSettings   *message,
                      ProtobufCBuffer     *buffer);
Livekit__UpdateTrackSettings *
       livekit__update_track_settings__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__update_track_settings__free_unpacked
                     (Livekit__UpdateTrackSettings *message,
                      ProtobufCAllocator *allocator);
/* Livekit__UpdateLocalAudioTrack methods */
void   livekit__update_local_audio_track__init
                     (Livekit__UpdateLocalAudioTrack         *message);
size_t livekit__update_local_audio_track__get_packed_size
                     (const Livekit__UpdateLocalAudioTrack   *message);
size_t livekit__update_local_audio_track__pack
                     (const Livekit__UpdateLocalAudioTrack   *message,
                      uint8_t             *out);
size_t livekit__update_local_audio_track__pack_to_buffer
                     (const Livekit__UpdateLocalAudioTrack   *message,
                      ProtobufCBuffer     *buffer);
Livekit__UpdateLocalAudioTrack *
       livekit__update_local_audio_track__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__update_local_audio_track__free_unpacked
                     (Livekit__UpdateLocalAudioTrack *message,
                      ProtobufCAllocator *allocator);
/* Livekit__UpdateLocalVideoTrack methods */
void   livekit__update_local_video_track__init
                     (Livekit__UpdateLocalVideoTrack         *message);
size_t livekit__update_local_video_track__get_packed_size
                     (const Livekit__UpdateLocalVideoTrack   *message);
size_t livekit__update_local_video_track__pack
                     (const Livekit__UpdateLocalVideoTrack   *message,
                      uint8_t             *out);
size_t livekit__update_local_video_track__pack_to_buffer
                     (const Livekit__UpdateLocalVideoTrack   *message,
                      ProtobufCBuffer     *buffer);
Livekit__UpdateLocalVideoTrack *
       livekit__update_local_video_track__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__update_local_video_track__free_unpacked
                     (Livekit__UpdateLocalVideoTrack *message,
                      ProtobufCAllocator *allocator);
/* Livekit__LeaveRequest methods */
void   livekit__leave_request__init
                     (Livekit__LeaveRequest         *message);
size_t livekit__leave_request__get_packed_size
                     (const Livekit__LeaveRequest   *message);
size_t livekit__leave_request__pack
                     (const Livekit__LeaveRequest   *message,
                      uint8_t             *out);
size_t livekit__leave_request__pack_to_buffer
                     (const Livekit__LeaveRequest   *message,
                      ProtobufCBuffer     *buffer);
Livekit__LeaveRequest *
       livekit__leave_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__leave_request__free_unpacked
                     (Livekit__LeaveRequest *message,
                      ProtobufCAllocator *allocator);
/* Livekit__UpdateVideoLayers methods */
void   livekit__update_video_layers__init
                     (Livekit__UpdateVideoLayers         *message);
size_t livekit__update_video_layers__get_packed_size
                     (const Livekit__UpdateVideoLayers   *message);
size_t livekit__update_video_layers__pack
                     (const Livekit__UpdateVideoLayers   *message,
                      uint8_t             *out);
size_t livekit__update_video_layers__pack_to_buffer
                     (const Livekit__UpdateVideoLayers   *message,
                      ProtobufCBuffer     *buffer);
Livekit__UpdateVideoLayers *
       livekit__update_video_layers__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__update_video_layers__free_unpacked
                     (Livekit__UpdateVideoLayers *message,
                      ProtobufCAllocator *allocator);
/* Livekit__UpdateParticipantMetadata__AttributesEntry methods */
void   livekit__update_participant_metadata__attributes_entry__init
                     (Livekit__UpdateParticipantMetadata__AttributesEntry         *message);
/* Livekit__UpdateParticipantMetadata methods */
void   livekit__update_participant_metadata__init
                     (Livekit__UpdateParticipantMetadata         *message);
size_t livekit__update_participant_metadata__get_packed_size
                     (const Livekit__UpdateParticipantMetadata   *message);
size_t livekit__update_participant_metadata__pack
                     (const Livekit__UpdateParticipantMetadata   *message,
                      uint8_t             *out);
size_t livekit__update_participant_metadata__pack_to_buffer
                     (const Livekit__UpdateParticipantMetadata   *message,
                      ProtobufCBuffer     *buffer);
Livekit__UpdateParticipantMetadata *
       livekit__update_participant_metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__update_participant_metadata__free_unpacked
                     (Livekit__UpdateParticipantMetadata *message,
                      ProtobufCAllocator *allocator);
/* Livekit__ICEServer methods */
void   livekit__iceserver__init
                     (Livekit__ICEServer         *message);
size_t livekit__iceserver__get_packed_size
                     (const Livekit__ICEServer   *message);
size_t livekit__iceserver__pack
                     (const Livekit__ICEServer   *message,
                      uint8_t             *out);
size_t livekit__iceserver__pack_to_buffer
                     (const Livekit__ICEServer   *message,
                      ProtobufCBuffer     *buffer);
Livekit__ICEServer *
       livekit__iceserver__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__iceserver__free_unpacked
                     (Livekit__ICEServer *message,
                      ProtobufCAllocator *allocator);
/* Livekit__SpeakersChanged methods */
void   livekit__speakers_changed__init
                     (Livekit__SpeakersChanged         *message);
size_t livekit__speakers_changed__get_packed_size
                     (const Livekit__SpeakersChanged   *message);
size_t livekit__speakers_changed__pack
                     (const Livekit__SpeakersChanged   *message,
                      uint8_t             *out);
size_t livekit__speakers_changed__pack_to_buffer
                     (const Livekit__SpeakersChanged   *message,
                      ProtobufCBuffer     *buffer);
Livekit__SpeakersChanged *
       livekit__speakers_changed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__speakers_changed__free_unpacked
                     (Livekit__SpeakersChanged *message,
                      ProtobufCAllocator *allocator);
/* Livekit__RoomUpdate methods */
void   livekit__room_update__init
                     (Livekit__RoomUpdate         *message);
size_t livekit__room_update__get_packed_size
                     (const Livekit__RoomUpdate   *message);
size_t livekit__room_update__pack
                     (const Livekit__RoomUpdate   *message,
                      uint8_t             *out);
size_t livekit__room_update__pack_to_buffer
                     (const Livekit__RoomUpdate   *message,
                      ProtobufCBuffer     *buffer);
Livekit__RoomUpdate *
       livekit__room_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__room_update__free_unpacked
                     (Livekit__RoomUpdate *message,
                      ProtobufCAllocator *allocator);
/* Livekit__ConnectionQualityInfo methods */
void   livekit__connection_quality_info__init
                     (Livekit__ConnectionQualityInfo         *message);
size_t livekit__connection_quality_info__get_packed_size
                     (const Livekit__ConnectionQualityInfo   *message);
size_t livekit__connection_quality_info__pack
                     (const Livekit__ConnectionQualityInfo   *message,
                      uint8_t             *out);
size_t livekit__connection_quality_info__pack_to_buffer
                     (const Livekit__ConnectionQualityInfo   *message,
                      ProtobufCBuffer     *buffer);
Livekit__ConnectionQualityInfo *
       livekit__connection_quality_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__connection_quality_info__free_unpacked
                     (Livekit__ConnectionQualityInfo *message,
                      ProtobufCAllocator *allocator);
/* Livekit__ConnectionQualityUpdate methods */
void   livekit__connection_quality_update__init
                     (Livekit__ConnectionQualityUpdate         *message);
size_t livekit__connection_quality_update__get_packed_size
                     (const Livekit__ConnectionQualityUpdate   *message);
size_t livekit__connection_quality_update__pack
                     (const Livekit__ConnectionQualityUpdate   *message,
                      uint8_t             *out);
size_t livekit__connection_quality_update__pack_to_buffer
                     (const Livekit__ConnectionQualityUpdate   *message,
                      ProtobufCBuffer     *buffer);
Livekit__ConnectionQualityUpdate *
       livekit__connection_quality_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__connection_quality_update__free_unpacked
                     (Livekit__ConnectionQualityUpdate *message,
                      ProtobufCAllocator *allocator);
/* Livekit__StreamStateInfo methods */
void   livekit__stream_state_info__init
                     (Livekit__StreamStateInfo         *message);
size_t livekit__stream_state_info__get_packed_size
                     (const Livekit__StreamStateInfo   *message);
size_t livekit__stream_state_info__pack
                     (const Livekit__StreamStateInfo   *message,
                      uint8_t             *out);
size_t livekit__stream_state_info__pack_to_buffer
                     (const Livekit__StreamStateInfo   *message,
                      ProtobufCBuffer     *buffer);
Livekit__StreamStateInfo *
       livekit__stream_state_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__stream_state_info__free_unpacked
                     (Livekit__StreamStateInfo *message,
                      ProtobufCAllocator *allocator);
/* Livekit__StreamStateUpdate methods */
void   livekit__stream_state_update__init
                     (Livekit__StreamStateUpdate         *message);
size_t livekit__stream_state_update__get_packed_size
                     (const Livekit__StreamStateUpdate   *message);
size_t livekit__stream_state_update__pack
                     (const Livekit__StreamStateUpdate   *message,
                      uint8_t             *out);
size_t livekit__stream_state_update__pack_to_buffer
                     (const Livekit__StreamStateUpdate   *message,
                      ProtobufCBuffer     *buffer);
Livekit__StreamStateUpdate *
       livekit__stream_state_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__stream_state_update__free_unpacked
                     (Livekit__StreamStateUpdate *message,
                      ProtobufCAllocator *allocator);
/* Livekit__SubscribedQuality methods */
void   livekit__subscribed_quality__init
                     (Livekit__SubscribedQuality         *message);
size_t livekit__subscribed_quality__get_packed_size
                     (const Livekit__SubscribedQuality   *message);
size_t livekit__subscribed_quality__pack
                     (const Livekit__SubscribedQuality   *message,
                      uint8_t             *out);
size_t livekit__subscribed_quality__pack_to_buffer
                     (const Livekit__SubscribedQuality   *message,
                      ProtobufCBuffer     *buffer);
Livekit__SubscribedQuality *
       livekit__subscribed_quality__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__subscribed_quality__free_unpacked
                     (Livekit__SubscribedQuality *message,
                      ProtobufCAllocator *allocator);
/* Livekit__SubscribedCodec methods */
void   livekit__subscribed_codec__init
                     (Livekit__SubscribedCodec         *message);
size_t livekit__subscribed_codec__get_packed_size
                     (const Livekit__SubscribedCodec   *message);
size_t livekit__subscribed_codec__pack
                     (const Livekit__SubscribedCodec   *message,
                      uint8_t             *out);
size_t livekit__subscribed_codec__pack_to_buffer
                     (const Livekit__SubscribedCodec   *message,
                      ProtobufCBuffer     *buffer);
Livekit__SubscribedCodec *
       livekit__subscribed_codec__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__subscribed_codec__free_unpacked
                     (Livekit__SubscribedCodec *message,
                      ProtobufCAllocator *allocator);
/* Livekit__SubscribedQualityUpdate methods */
void   livekit__subscribed_quality_update__init
                     (Livekit__SubscribedQualityUpdate         *message);
size_t livekit__subscribed_quality_update__get_packed_size
                     (const Livekit__SubscribedQualityUpdate   *message);
size_t livekit__subscribed_quality_update__pack
                     (const Livekit__SubscribedQualityUpdate   *message,
                      uint8_t             *out);
size_t livekit__subscribed_quality_update__pack_to_buffer
                     (const Livekit__SubscribedQualityUpdate   *message,
                      ProtobufCBuffer     *buffer);
Livekit__SubscribedQualityUpdate *
       livekit__subscribed_quality_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__subscribed_quality_update__free_unpacked
                     (Livekit__SubscribedQualityUpdate *message,
                      ProtobufCAllocator *allocator);
/* Livekit__TrackPermission methods */
void   livekit__track_permission__init
                     (Livekit__TrackPermission         *message);
size_t livekit__track_permission__get_packed_size
                     (const Livekit__TrackPermission   *message);
size_t livekit__track_permission__pack
                     (const Livekit__TrackPermission   *message,
                      uint8_t             *out);
size_t livekit__track_permission__pack_to_buffer
                     (const Livekit__TrackPermission   *message,
                      ProtobufCBuffer     *buffer);
Livekit__TrackPermission *
       livekit__track_permission__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__track_permission__free_unpacked
                     (Livekit__TrackPermission *message,
                      ProtobufCAllocator *allocator);
/* Livekit__SubscriptionPermission methods */
void   livekit__subscription_permission__init
                     (Livekit__SubscriptionPermission         *message);
size_t livekit__subscription_permission__get_packed_size
                     (const Livekit__SubscriptionPermission   *message);
size_t livekit__subscription_permission__pack
                     (const Livekit__SubscriptionPermission   *message,
                      uint8_t             *out);
size_t livekit__subscription_permission__pack_to_buffer
                     (const Livekit__SubscriptionPermission   *message,
                      ProtobufCBuffer     *buffer);
Livekit__SubscriptionPermission *
       livekit__subscription_permission__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__subscription_permission__free_unpacked
                     (Livekit__SubscriptionPermission *message,
                      ProtobufCAllocator *allocator);
/* Livekit__SubscriptionPermissionUpdate methods */
void   livekit__subscription_permission_update__init
                     (Livekit__SubscriptionPermissionUpdate         *message);
size_t livekit__subscription_permission_update__get_packed_size
                     (const Livekit__SubscriptionPermissionUpdate   *message);
size_t livekit__subscription_permission_update__pack
                     (const Livekit__SubscriptionPermissionUpdate   *message,
                      uint8_t             *out);
size_t livekit__subscription_permission_update__pack_to_buffer
                     (const Livekit__SubscriptionPermissionUpdate   *message,
                      ProtobufCBuffer     *buffer);
Livekit__SubscriptionPermissionUpdate *
       livekit__subscription_permission_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__subscription_permission_update__free_unpacked
                     (Livekit__SubscriptionPermissionUpdate *message,
                      ProtobufCAllocator *allocator);
/* Livekit__RoomMovedResponse methods */
void   livekit__room_moved_response__init
                     (Livekit__RoomMovedResponse         *message);
size_t livekit__room_moved_response__get_packed_size
                     (const Livekit__RoomMovedResponse   *message);
size_t livekit__room_moved_response__pack
                     (const Livekit__RoomMovedResponse   *message,
                      uint8_t             *out);
size_t livekit__room_moved_response__pack_to_buffer
                     (const Livekit__RoomMovedResponse   *message,
                      ProtobufCBuffer     *buffer);
Livekit__RoomMovedResponse *
       livekit__room_moved_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__room_moved_response__free_unpacked
                     (Livekit__RoomMovedResponse *message,
                      ProtobufCAllocator *allocator);
/* Livekit__SyncState methods */
void   livekit__sync_state__init
                     (Livekit__SyncState         *message);
size_t livekit__sync_state__get_packed_size
                     (const Livekit__SyncState   *message);
size_t livekit__sync_state__pack
                     (const Livekit__SyncState   *message,
                      uint8_t             *out);
size_t livekit__sync_state__pack_to_buffer
                     (const Livekit__SyncState   *message,
                      ProtobufCBuffer     *buffer);
Livekit__SyncState *
       livekit__sync_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__sync_state__free_unpacked
                     (Livekit__SyncState *message,
                      ProtobufCAllocator *allocator);
/* Livekit__DataChannelReceiveState methods */
void   livekit__data_channel_receive_state__init
                     (Livekit__DataChannelReceiveState         *message);
size_t livekit__data_channel_receive_state__get_packed_size
                     (const Livekit__DataChannelReceiveState   *message);
size_t livekit__data_channel_receive_state__pack
                     (const Livekit__DataChannelReceiveState   *message,
                      uint8_t             *out);
size_t livekit__data_channel_receive_state__pack_to_buffer
                     (const Livekit__DataChannelReceiveState   *message,
                      ProtobufCBuffer     *buffer);
Livekit__DataChannelReceiveState *
       livekit__data_channel_receive_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__data_channel_receive_state__free_unpacked
                     (Livekit__DataChannelReceiveState *message,
                      ProtobufCAllocator *allocator);
/* Livekit__DataChannelInfo methods */
void   livekit__data_channel_info__init
                     (Livekit__DataChannelInfo         *message);
size_t livekit__data_channel_info__get_packed_size
                     (const Livekit__DataChannelInfo   *message);
size_t livekit__data_channel_info__pack
                     (const Livekit__DataChannelInfo   *message,
                      uint8_t             *out);
size_t livekit__data_channel_info__pack_to_buffer
                     (const Livekit__DataChannelInfo   *message,
                      ProtobufCBuffer     *buffer);
Livekit__DataChannelInfo *
       livekit__data_channel_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__data_channel_info__free_unpacked
                     (Livekit__DataChannelInfo *message,
                      ProtobufCAllocator *allocator);
/* Livekit__SimulateScenario methods */
void   livekit__simulate_scenario__init
                     (Livekit__SimulateScenario         *message);
size_t livekit__simulate_scenario__get_packed_size
                     (const Livekit__SimulateScenario   *message);
size_t livekit__simulate_scenario__pack
                     (const Livekit__SimulateScenario   *message,
                      uint8_t             *out);
size_t livekit__simulate_scenario__pack_to_buffer
                     (const Livekit__SimulateScenario   *message,
                      ProtobufCBuffer     *buffer);
Livekit__SimulateScenario *
       livekit__simulate_scenario__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__simulate_scenario__free_unpacked
                     (Livekit__SimulateScenario *message,
                      ProtobufCAllocator *allocator);
/* Livekit__Ping methods */
void   livekit__ping__init
                     (Livekit__Ping         *message);
size_t livekit__ping__get_packed_size
                     (const Livekit__Ping   *message);
size_t livekit__ping__pack
                     (const Livekit__Ping   *message,
                      uint8_t             *out);
size_t livekit__ping__pack_to_buffer
                     (const Livekit__Ping   *message,
                      ProtobufCBuffer     *buffer);
Livekit__Ping *
       livekit__ping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__ping__free_unpacked
                     (Livekit__Ping *message,
                      ProtobufCAllocator *allocator);
/* Livekit__Pong methods */
void   livekit__pong__init
                     (Livekit__Pong         *message);
size_t livekit__pong__get_packed_size
                     (const Livekit__Pong   *message);
size_t livekit__pong__pack
                     (const Livekit__Pong   *message,
                      uint8_t             *out);
size_t livekit__pong__pack_to_buffer
                     (const Livekit__Pong   *message,
                      ProtobufCBuffer     *buffer);
Livekit__Pong *
       livekit__pong__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__pong__free_unpacked
                     (Livekit__Pong *message,
                      ProtobufCAllocator *allocator);
/* Livekit__RegionSettings methods */
void   livekit__region_settings__init
                     (Livekit__RegionSettings         *message);
size_t livekit__region_settings__get_packed_size
                     (const Livekit__RegionSettings   *message);
size_t livekit__region_settings__pack
                     (const Livekit__RegionSettings   *message,
                      uint8_t             *out);
size_t livekit__region_settings__pack_to_buffer
                     (const Livekit__RegionSettings   *message,
                      ProtobufCBuffer     *buffer);
Livekit__RegionSettings *
       livekit__region_settings__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__region_settings__free_unpacked
                     (Livekit__RegionSettings *message,
                      ProtobufCAllocator *allocator);
/* Livekit__RegionInfo methods */
void   livekit__region_info__init
                     (Livekit__RegionInfo         *message);
size_t livekit__region_info__get_packed_size
                     (const Livekit__RegionInfo   *message);
size_t livekit__region_info__pack
                     (const Livekit__RegionInfo   *message,
                      uint8_t             *out);
size_t livekit__region_info__pack_to_buffer
                     (const Livekit__RegionInfo   *message,
                      ProtobufCBuffer     *buffer);
Livekit__RegionInfo *
       livekit__region_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__region_info__free_unpacked
                     (Livekit__RegionInfo *message,
                      ProtobufCAllocator *allocator);
/* Livekit__SubscriptionResponse methods */
void   livekit__subscription_response__init
                     (Livekit__SubscriptionResponse         *message);
size_t livekit__subscription_response__get_packed_size
                     (const Livekit__SubscriptionResponse   *message);
size_t livekit__subscription_response__pack
                     (const Livekit__SubscriptionResponse   *message,
                      uint8_t             *out);
size_t livekit__subscription_response__pack_to_buffer
                     (const Livekit__SubscriptionResponse   *message,
                      ProtobufCBuffer     *buffer);
Livekit__SubscriptionResponse *
       livekit__subscription_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__subscription_response__free_unpacked
                     (Livekit__SubscriptionResponse *message,
                      ProtobufCAllocator *allocator);
/* Livekit__RequestResponse methods */
void   livekit__request_response__init
                     (Livekit__RequestResponse         *message);
size_t livekit__request_response__get_packed_size
                     (const Livekit__RequestResponse   *message);
size_t livekit__request_response__pack
                     (const Livekit__RequestResponse   *message,
                      uint8_t             *out);
size_t livekit__request_response__pack_to_buffer
                     (const Livekit__RequestResponse   *message,
                      ProtobufCBuffer     *buffer);
Livekit__RequestResponse *
       livekit__request_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__request_response__free_unpacked
                     (Livekit__RequestResponse *message,
                      ProtobufCAllocator *allocator);
/* Livekit__TrackSubscribed methods */
void   livekit__track_subscribed__init
                     (Livekit__TrackSubscribed         *message);
size_t livekit__track_subscribed__get_packed_size
                     (const Livekit__TrackSubscribed   *message);
size_t livekit__track_subscribed__pack
                     (const Livekit__TrackSubscribed   *message,
                      uint8_t             *out);
size_t livekit__track_subscribed__pack_to_buffer
                     (const Livekit__TrackSubscribed   *message,
                      ProtobufCBuffer     *buffer);
Livekit__TrackSubscribed *
       livekit__track_subscribed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__track_subscribed__free_unpacked
                     (Livekit__TrackSubscribed *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Livekit__SignalRequest_Closure)
                 (const Livekit__SignalRequest *message,
                  void *closure_data);
typedef void (*Livekit__SignalResponse_Closure)
                 (const Livekit__SignalResponse *message,
                  void *closure_data);
typedef void (*Livekit__SimulcastCodec_Closure)
                 (const Livekit__SimulcastCodec *message,
                  void *closure_data);
typedef void (*Livekit__AddTrackRequest_Closure)
                 (const Livekit__AddTrackRequest *message,
                  void *closure_data);
typedef void (*Livekit__TrickleRequest_Closure)
                 (const Livekit__TrickleRequest *message,
                  void *closure_data);
typedef void (*Livekit__MuteTrackRequest_Closure)
                 (const Livekit__MuteTrackRequest *message,
                  void *closure_data);
typedef void (*Livekit__JoinResponse_Closure)
                 (const Livekit__JoinResponse *message,
                  void *closure_data);
typedef void (*Livekit__ReconnectResponse_Closure)
                 (const Livekit__ReconnectResponse *message,
                  void *closure_data);
typedef void (*Livekit__TrackPublishedResponse_Closure)
                 (const Livekit__TrackPublishedResponse *message,
                  void *closure_data);
typedef void (*Livekit__TrackUnpublishedResponse_Closure)
                 (const Livekit__TrackUnpublishedResponse *message,
                  void *closure_data);
typedef void (*Livekit__SessionDescription_Closure)
                 (const Livekit__SessionDescription *message,
                  void *closure_data);
typedef void (*Livekit__ParticipantUpdate_Closure)
                 (const Livekit__ParticipantUpdate *message,
                  void *closure_data);
typedef void (*Livekit__UpdateSubscription_Closure)
                 (const Livekit__UpdateSubscription *message,
                  void *closure_data);
typedef void (*Livekit__UpdateTrackSettings_Closure)
                 (const Livekit__UpdateTrackSettings *message,
                  void *closure_data);
typedef void (*Livekit__UpdateLocalAudioTrack_Closure)
                 (const Livekit__UpdateLocalAudioTrack *message,
                  void *closure_data);
typedef void (*Livekit__UpdateLocalVideoTrack_Closure)
                 (const Livekit__UpdateLocalVideoTrack *message,
                  void *closure_data);
typedef void (*Livekit__LeaveRequest_Closure)
                 (const Livekit__LeaveRequest *message,
                  void *closure_data);
typedef void (*Livekit__UpdateVideoLayers_Closure)
                 (const Livekit__UpdateVideoLayers *message,
                  void *closure_data);
typedef void (*Livekit__UpdateParticipantMetadata__AttributesEntry_Closure)
                 (const Livekit__UpdateParticipantMetadata__AttributesEntry *message,
                  void *closure_data);
typedef void (*Livekit__UpdateParticipantMetadata_Closure)
                 (const Livekit__UpdateParticipantMetadata *message,
                  void *closure_data);
typedef void (*Livekit__ICEServer_Closure)
                 (const Livekit__ICEServer *message,
                  void *closure_data);
typedef void (*Livekit__SpeakersChanged_Closure)
                 (const Livekit__SpeakersChanged *message,
                  void *closure_data);
typedef void (*Livekit__RoomUpdate_Closure)
                 (const Livekit__RoomUpdate *message,
                  void *closure_data);
typedef void (*Livekit__ConnectionQualityInfo_Closure)
                 (const Livekit__ConnectionQualityInfo *message,
                  void *closure_data);
typedef void (*Livekit__ConnectionQualityUpdate_Closure)
                 (const Livekit__ConnectionQualityUpdate *message,
                  void *closure_data);
typedef void (*Livekit__StreamStateInfo_Closure)
                 (const Livekit__StreamStateInfo *message,
                  void *closure_data);
typedef void (*Livekit__StreamStateUpdate_Closure)
                 (const Livekit__StreamStateUpdate *message,
                  void *closure_data);
typedef void (*Livekit__SubscribedQuality_Closure)
                 (const Livekit__SubscribedQuality *message,
                  void *closure_data);
typedef void (*Livekit__SubscribedCodec_Closure)
                 (const Livekit__SubscribedCodec *message,
                  void *closure_data);
typedef void (*Livekit__SubscribedQualityUpdate_Closure)
                 (const Livekit__SubscribedQualityUpdate *message,
                  void *closure_data);
typedef void (*Livekit__TrackPermission_Closure)
                 (const Livekit__TrackPermission *message,
                  void *closure_data);
typedef void (*Livekit__SubscriptionPermission_Closure)
                 (const Livekit__SubscriptionPermission *message,
                  void *closure_data);
typedef void (*Livekit__SubscriptionPermissionUpdate_Closure)
                 (const Livekit__SubscriptionPermissionUpdate *message,
                  void *closure_data);
typedef void (*Livekit__RoomMovedResponse_Closure)
                 (const Livekit__RoomMovedResponse *message,
                  void *closure_data);
typedef void (*Livekit__SyncState_Closure)
                 (const Livekit__SyncState *message,
                  void *closure_data);
typedef void (*Livekit__DataChannelReceiveState_Closure)
                 (const Livekit__DataChannelReceiveState *message,
                  void *closure_data);
typedef void (*Livekit__DataChannelInfo_Closure)
                 (const Livekit__DataChannelInfo *message,
                  void *closure_data);
typedef void (*Livekit__SimulateScenario_Closure)
                 (const Livekit__SimulateScenario *message,
                  void *closure_data);
typedef void (*Livekit__Ping_Closure)
                 (const Livekit__Ping *message,
                  void *closure_data);
typedef void (*Livekit__Pong_Closure)
                 (const Livekit__Pong *message,
                  void *closure_data);
typedef void (*Livekit__RegionSettings_Closure)
                 (const Livekit__RegionSettings *message,
                  void *closure_data);
typedef void (*Livekit__RegionInfo_Closure)
                 (const Livekit__RegionInfo *message,
                  void *closure_data);
typedef void (*Livekit__SubscriptionResponse_Closure)
                 (const Livekit__SubscriptionResponse *message,
                  void *closure_data);
typedef void (*Livekit__RequestResponse_Closure)
                 (const Livekit__RequestResponse *message,
                  void *closure_data);
typedef void (*Livekit__TrackSubscribed_Closure)
                 (const Livekit__TrackSubscribed *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    livekit__signal_target__descriptor;
extern const ProtobufCEnumDescriptor    livekit__stream_state__descriptor;
extern const ProtobufCEnumDescriptor    livekit__candidate_protocol__descriptor;
extern const ProtobufCMessageDescriptor livekit__signal_request__descriptor;
extern const ProtobufCMessageDescriptor livekit__signal_response__descriptor;
extern const ProtobufCMessageDescriptor livekit__simulcast_codec__descriptor;
extern const ProtobufCMessageDescriptor livekit__add_track_request__descriptor;
extern const ProtobufCMessageDescriptor livekit__trickle_request__descriptor;
extern const ProtobufCMessageDescriptor livekit__mute_track_request__descriptor;
extern const ProtobufCMessageDescriptor livekit__join_response__descriptor;
extern const ProtobufCMessageDescriptor livekit__reconnect_response__descriptor;
extern const ProtobufCMessageDescriptor livekit__track_published_response__descriptor;
extern const ProtobufCMessageDescriptor livekit__track_unpublished_response__descriptor;
extern const ProtobufCMessageDescriptor livekit__session_description__descriptor;
extern const ProtobufCMessageDescriptor livekit__participant_update__descriptor;
extern const ProtobufCMessageDescriptor livekit__update_subscription__descriptor;
extern const ProtobufCMessageDescriptor livekit__update_track_settings__descriptor;
extern const ProtobufCMessageDescriptor livekit__update_local_audio_track__descriptor;
extern const ProtobufCMessageDescriptor livekit__update_local_video_track__descriptor;
extern const ProtobufCMessageDescriptor livekit__leave_request__descriptor;
extern const ProtobufCEnumDescriptor    livekit__leave_request__action__descriptor;
extern const ProtobufCMessageDescriptor livekit__update_video_layers__descriptor;
extern const ProtobufCMessageDescriptor livekit__update_participant_metadata__descriptor;
extern const ProtobufCMessageDescriptor livekit__update_participant_metadata__attributes_entry__descriptor;
extern const ProtobufCMessageDescriptor livekit__iceserver__descriptor;
extern const ProtobufCMessageDescriptor livekit__speakers_changed__descriptor;
extern const ProtobufCMessageDescriptor livekit__room_update__descriptor;
extern const ProtobufCMessageDescriptor livekit__connection_quality_info__descriptor;
extern const ProtobufCMessageDescriptor livekit__connection_quality_update__descriptor;
extern const ProtobufCMessageDescriptor livekit__stream_state_info__descriptor;
extern const ProtobufCMessageDescriptor livekit__stream_state_update__descriptor;
extern const ProtobufCMessageDescriptor livekit__subscribed_quality__descriptor;
extern const ProtobufCMessageDescriptor livekit__subscribed_codec__descriptor;
extern const ProtobufCMessageDescriptor livekit__subscribed_quality_update__descriptor;
extern const ProtobufCMessageDescriptor livekit__track_permission__descriptor;
extern const ProtobufCMessageDescriptor livekit__subscription_permission__descriptor;
extern const ProtobufCMessageDescriptor livekit__subscription_permission_update__descriptor;
extern const ProtobufCMessageDescriptor livekit__room_moved_response__descriptor;
extern const ProtobufCMessageDescriptor livekit__sync_state__descriptor;
extern const ProtobufCMessageDescriptor livekit__data_channel_receive_state__descriptor;
extern const ProtobufCMessageDescriptor livekit__data_channel_info__descriptor;
extern const ProtobufCMessageDescriptor livekit__simulate_scenario__descriptor;
extern const ProtobufCMessageDescriptor livekit__ping__descriptor;
extern const ProtobufCMessageDescriptor livekit__pong__descriptor;
extern const ProtobufCMessageDescriptor livekit__region_settings__descriptor;
extern const ProtobufCMessageDescriptor livekit__region_info__descriptor;
extern const ProtobufCMessageDescriptor livekit__subscription_response__descriptor;
extern const ProtobufCMessageDescriptor livekit__request_response__descriptor;
extern const ProtobufCEnumDescriptor    livekit__request_response__reason__descriptor;
extern const ProtobufCMessageDescriptor livekit__track_subscribed__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_livekit_5frtc_2eproto__INCLUDED */
