/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: livekit_metrics.proto */

#ifndef PROTOBUF_C_livekit_5fmetrics_2eproto__INCLUDED
#define PROTOBUF_C_livekit_5fmetrics_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "google/protobuf/timestamp.pb-c.h"

typedef struct Livekit__MetricsBatch Livekit__MetricsBatch;
typedef struct Livekit__TimeSeriesMetric Livekit__TimeSeriesMetric;
typedef struct Livekit__MetricSample Livekit__MetricSample;
typedef struct Livekit__EventMetric Livekit__EventMetric;


/* --- enums --- */

/*
 * index from [0: MAX_LABEL_PREDEFINED_MAX_VALUE) are for predefined labels (`MetricLabel`)
 */
typedef enum _Livekit__MetricLabel {
  /*
   * time to first token from LLM
   */
  LIVEKIT__METRIC_LABEL__AGENTS_LLM_TTFT = 0,
  /*
   * time to final transcription
   */
  LIVEKIT__METRIC_LABEL__AGENTS_STT_TTFT = 1,
  /*
   * time to first byte
   */
  LIVEKIT__METRIC_LABEL__AGENTS_TTS_TTFB = 2,
  /*
   * Number of video freezes
   */
  LIVEKIT__METRIC_LABEL__CLIENT_VIDEO_SUBSCRIBER_FREEZE_COUNT = 3,
  /*
   * total duration of freezes
   */
  LIVEKIT__METRIC_LABEL__CLIENT_VIDEO_SUBSCRIBER_TOTAL_FREEZE_DURATION = 4,
  /*
   * number of video pauses
   */
  LIVEKIT__METRIC_LABEL__CLIENT_VIDEO_SUBSCRIBER_PAUSE_COUNT = 5,
  /*
   * total duration of pauses
   */
  LIVEKIT__METRIC_LABEL__CLIENT_VIDEO_SUBSCRIBER_TOTAL_PAUSES_DURATION = 6,
  /*
   * number of concealed (synthesized) audio samples
   */
  LIVEKIT__METRIC_LABEL__CLIENT_AUDIO_SUBSCRIBER_CONCEALED_SAMPLES = 7,
  /*
   * number of silent concealed samples
   */
  LIVEKIT__METRIC_LABEL__CLIENT_AUDIO_SUBSCRIBER_SILENT_CONCEALED_SAMPLES = 8,
  /*
   * number of concealment events
   */
  LIVEKIT__METRIC_LABEL__CLIENT_AUDIO_SUBSCRIBER_CONCEALMENT_EVENTS = 9,
  /*
   * number of interruptions
   */
  LIVEKIT__METRIC_LABEL__CLIENT_AUDIO_SUBSCRIBER_INTERRUPTION_COUNT = 10,
  /*
   * total duration of interruptions
   */
  LIVEKIT__METRIC_LABEL__CLIENT_AUDIO_SUBSCRIBER_TOTAL_INTERRUPTION_DURATION = 11,
  /*
   * total time spent in jitter buffer
   */
  LIVEKIT__METRIC_LABEL__CLIENT_SUBSCRIBER_JITTER_BUFFER_DELAY = 12,
  /*
   * total time spent in jitter buffer
   */
  LIVEKIT__METRIC_LABEL__CLIENT_SUBSCRIBER_JITTER_BUFFER_EMITTED_COUNT = 13,
  /*
   * total duration spent in bandwidth quality limitation
   */
  LIVEKIT__METRIC_LABEL__CLIENT_VIDEO_PUBLISHER_QUALITY_LIMITATION_DURATION_BANDWIDTH = 14,
  /*
   * total duration spent in cpu quality limitation
   */
  LIVEKIT__METRIC_LABEL__CLIENT_VIDEO_PUBLISHER_QUALITY_LIMITATION_DURATION_CPU = 15,
  /*
   * total duration spent in other quality limitation
   */
  LIVEKIT__METRIC_LABEL__CLIENT_VIDEO_PUBLISHER_QUALITY_LIMITATION_DURATION_OTHER = 16,
  /*
   * Publisher RTT (participant -> server)
   */
  LIVEKIT__METRIC_LABEL__PUBLISHER_RTT = 17,
  /*
   * RTT between publisher node and subscriber node (could involve intermedia node(s))
   */
  LIVEKIT__METRIC_LABEL__SERVER_MESH_RTT = 18,
  /*
   * Subscribe RTT (server -> participant)
   */
  LIVEKIT__METRIC_LABEL__SUBSCRIBER_RTT = 19,
  LIVEKIT__METRIC_LABEL__METRIC_LABEL_PREDEFINED_MAX_VALUE = 4096
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__METRIC_LABEL)
} Livekit__MetricLabel;

/* --- messages --- */

struct  Livekit__MetricsBatch
{
  ProtobufCMessage base;
  /*
   * time at which this batch is sent based on a monotonic clock (millisecond resolution)
   */
  int64_t timestamp_ms;
  Google__Protobuf__Timestamp *normalized_timestamp;
  /*
   * To avoid repeating string values, we store them in a separate list and reference them by index
   * This is useful for storing participant identities, track names, etc.
   * There is also a predefined list of labels that can be used to reference common metrics.
   * They have reserved indices from 0 to (METRIC_LABEL_PREDEFINED_MAX_VALUE - 1).
   * Indexes pointing at str_data should start from METRIC_LABEL_PREDEFINED_MAX_VALUE, 
   * such that str_data[0] == index of METRIC_LABEL_PREDEFINED_MAX_VALUE.
   */
  size_t n_str_data;
  char **str_data;
  size_t n_time_series;
  Livekit__TimeSeriesMetric **time_series;
  size_t n_events;
  Livekit__EventMetric **events;
};
#define LIVEKIT__METRICS_BATCH__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__metrics_batch__descriptor) \
, 0, NULL, 0,NULL, 0,NULL, 0,NULL }


struct  Livekit__TimeSeriesMetric
{
  ProtobufCMessage base;
  /*
   * Metric name e.g "speech_probablity". The string value is not directly stored in the message, but referenced by index
   * in the `str_data` field of `MetricsBatch`
   */
  uint32_t label;
  /*
   * index into `str_data`
   */
  uint32_t participant_identity;
  /*
   * index into `str_data`
   */
  uint32_t track_sid;
  size_t n_samples;
  Livekit__MetricSample **samples;
  /*
   * index into 'str_data'
   */
  uint32_t rid;
};
#define LIVEKIT__TIME_SERIES_METRIC__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__time_series_metric__descriptor) \
, 0, 0, 0, 0,NULL, 0 }


struct  Livekit__MetricSample
{
  ProtobufCMessage base;
  /*
   * time of metric based on a monotonic clock (in milliseconds)
   */
  int64_t timestamp_ms;
  Google__Protobuf__Timestamp *normalized_timestamp;
  float value;
};
#define LIVEKIT__METRIC_SAMPLE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__metric_sample__descriptor) \
, 0, NULL, 0 }


typedef enum {
  LIVEKIT__EVENT_METRIC___END_TIMESTAMP_MS__NOT_SET = 0,
  LIVEKIT__EVENT_METRIC___END_TIMESTAMP_MS_END_TIMESTAMP_MS = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__EVENT_METRIC___END_TIMESTAMP_MS__CASE)
} Livekit__EventMetric__EndTimestampMsCase;

typedef enum {
  LIVEKIT__EVENT_METRIC___NORMALIZED_END_TIMESTAMP__NOT_SET = 0,
  LIVEKIT__EVENT_METRIC___NORMALIZED_END_TIMESTAMP_NORMALIZED_END_TIMESTAMP = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIVEKIT__EVENT_METRIC___NORMALIZED_END_TIMESTAMP__CASE)
} Livekit__EventMetric__NormalizedEndTimestampCase;

struct  Livekit__EventMetric
{
  ProtobufCMessage base;
  uint32_t label;
  /*
   * index into `str_data`
   */
  uint32_t participant_identity;
  /*
   * index into `str_data`
   */
  uint32_t track_sid;
  /*
   * start time of event based on a monotonic clock (in milliseconds)
   */
  int64_t start_timestamp_ms;
  Google__Protobuf__Timestamp *normalized_start_timestamp;
  char *metadata;
  /*
   * index into 'str_data'
   */
  uint32_t rid;
  Livekit__EventMetric__EndTimestampMsCase _end_timestamp_ms_case;
  union {
    /*
     * end time of event based on a monotonic clock (in milliseconds), if needed
     */
    int64_t end_timestamp_ms;
  };
  Livekit__EventMetric__NormalizedEndTimestampCase _normalized_end_timestamp_case;
  union {
    Google__Protobuf__Timestamp *normalized_end_timestamp;
  };
};
#define LIVEKIT__EVENT_METRIC__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&livekit__event_metric__descriptor) \
, 0, 0, 0, 0, NULL, (char *)protobuf_c_empty_string, 0, LIVEKIT__EVENT_METRIC___END_TIMESTAMP_MS__NOT_SET, {0}, LIVEKIT__EVENT_METRIC___NORMALIZED_END_TIMESTAMP__NOT_SET, {0} }


/* Livekit__MetricsBatch methods */
void   livekit__metrics_batch__init
                     (Livekit__MetricsBatch         *message);
size_t livekit__metrics_batch__get_packed_size
                     (const Livekit__MetricsBatch   *message);
size_t livekit__metrics_batch__pack
                     (const Livekit__MetricsBatch   *message,
                      uint8_t             *out);
size_t livekit__metrics_batch__pack_to_buffer
                     (const Livekit__MetricsBatch   *message,
                      ProtobufCBuffer     *buffer);
Livekit__MetricsBatch *
       livekit__metrics_batch__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__metrics_batch__free_unpacked
                     (Livekit__MetricsBatch *message,
                      ProtobufCAllocator *allocator);
/* Livekit__TimeSeriesMetric methods */
void   livekit__time_series_metric__init
                     (Livekit__TimeSeriesMetric         *message);
size_t livekit__time_series_metric__get_packed_size
                     (const Livekit__TimeSeriesMetric   *message);
size_t livekit__time_series_metric__pack
                     (const Livekit__TimeSeriesMetric   *message,
                      uint8_t             *out);
size_t livekit__time_series_metric__pack_to_buffer
                     (const Livekit__TimeSeriesMetric   *message,
                      ProtobufCBuffer     *buffer);
Livekit__TimeSeriesMetric *
       livekit__time_series_metric__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__time_series_metric__free_unpacked
                     (Livekit__TimeSeriesMetric *message,
                      ProtobufCAllocator *allocator);
/* Livekit__MetricSample methods */
void   livekit__metric_sample__init
                     (Livekit__MetricSample         *message);
size_t livekit__metric_sample__get_packed_size
                     (const Livekit__MetricSample   *message);
size_t livekit__metric_sample__pack
                     (const Livekit__MetricSample   *message,
                      uint8_t             *out);
size_t livekit__metric_sample__pack_to_buffer
                     (const Livekit__MetricSample   *message,
                      ProtobufCBuffer     *buffer);
Livekit__MetricSample *
       livekit__metric_sample__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__metric_sample__free_unpacked
                     (Livekit__MetricSample *message,
                      ProtobufCAllocator *allocator);
/* Livekit__EventMetric methods */
void   livekit__event_metric__init
                     (Livekit__EventMetric         *message);
size_t livekit__event_metric__get_packed_size
                     (const Livekit__EventMetric   *message);
size_t livekit__event_metric__pack
                     (const Livekit__EventMetric   *message,
                      uint8_t             *out);
size_t livekit__event_metric__pack_to_buffer
                     (const Livekit__EventMetric   *message,
                      ProtobufCBuffer     *buffer);
Livekit__EventMetric *
       livekit__event_metric__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   livekit__event_metric__free_unpacked
                     (Livekit__EventMetric *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Livekit__MetricsBatch_Closure)
                 (const Livekit__MetricsBatch *message,
                  void *closure_data);
typedef void (*Livekit__TimeSeriesMetric_Closure)
                 (const Livekit__TimeSeriesMetric *message,
                  void *closure_data);
typedef void (*Livekit__MetricSample_Closure)
                 (const Livekit__MetricSample *message,
                  void *closure_data);
typedef void (*Livekit__EventMetric_Closure)
                 (const Livekit__EventMetric *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    livekit__metric_label__descriptor;
extern const ProtobufCMessageDescriptor livekit__metrics_batch__descriptor;
extern const ProtobufCMessageDescriptor livekit__time_series_metric__descriptor;
extern const ProtobufCMessageDescriptor livekit__metric_sample__descriptor;
extern const ProtobufCMessageDescriptor livekit__event_metric__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_livekit_5fmetrics_2eproto__INCLUDED */
